# German 德语 — curated core vocab with IPA + example sentences.
VOCAB = [
    ("Hallo", "/ˈhalo/", "你好", "Hello", "greetings",
     "Hallo! Wie geht es dir?", None,
     "你好！你怎么样？", "Hi! How are you?"),
    ("Guten Morgen", "/ˈɡuːtn̩ ˈmɔʁɡŋ̍/", "早上好", "Good morning", "greetings",
     "Guten Morgen, hast du gut geschlafen?", None,
     "早上好，睡得好吗？", "Good morning, did you sleep well?"),
    ("Guten Abend", "/ˈɡuːtn̩ ˈaːbn̩t/", "晚上好", "Good evening", "greetings",
     "Guten Abend, willkommen bei uns.", None,
     "晚上好，欢迎到我家。", "Good evening, welcome."),
    ("Danke", "/ˈdaŋkə/", "谢谢", "Thank you", "greetings",
     "Danke für deine Hilfe.", None,
     "谢谢你的帮助。", "Thanks for your help."),
    ("Bitte", "/ˈbɪtə/", "请／不客气", "Please / You're welcome", "greetings",
     "Bitte, gern geschehen.", None,
     "不客气，乐意效劳。", "You're welcome, happy to help."),
    ("Entschuldigung", "/ɛntˈʃʊldɪɡʊŋ/", "对不起／劳驾", "Sorry / Excuse me", "greetings",
     "Entschuldigung, wo ist der Bahnhof?", None,
     "请问，火车站在哪里？", "Excuse me, where is the station?"),
    ("Alles gut", "/ˈaləs ɡuːt/", "没事", "All good", "greetings",
     "Alles gut, kein Problem.", None,
     "没事，没问题。", "All good, no problem."),
    ("Auf Wiedersehen", "/aʊf ˈviːdɐˌzeːən/", "再见", "Goodbye", "greetings",
     "Auf Wiedersehen, bis bald.", None,
     "再见，回头见。", "Goodbye, see you soon."),

    ("Eins", "/aɪns/", "1", "One", "numbers",
     "Ich nehme nur eins.", None,
     "我只要一个。", "I'll just take one."),
    ("Zwei", "/tsvaɪ/", "2", "Two", "numbers",
     "Zwei Bier, bitte.", None,
     "两杯啤酒，谢谢。", "Two beers, please."),
    ("Drei", "/dʁaɪ/", "3", "Three", "numbers",
     "Ich warte seit drei Stunden.", None,
     "我等了三个小时。", "I've been waiting for three hours."),
    ("Zehn", "/tseːn/", "10", "Ten", "numbers",
     "Noch zehn Minuten.", None,
     "还有十分钟。", "Ten more minutes."),

    ("Heute", "/ˈhɔʏtə/", "今天", "Today", "time",
     "Heute ist mein Geburtstag.", None,
     "今天是我生日。", "Today is my birthday."),
    ("Morgen", "/ˈmɔʁɡn̩/", "明天", "Tomorrow", "time",
     "Bis morgen!", None,
     "明天见！", "See you tomorrow!"),
    ("Gestern", "/ˈɡɛstɐn/", "昨天", "Yesterday", "time",
     "Gestern war ich krank.", None,
     "昨天我生病了。", "I was sick yesterday."),
    ("Jetzt", "/jɛtst/", "现在", "Now", "time",
     "Wir müssen jetzt gehen.", None,
     "我们现在必须走。", "We have to go now."),
    ("Wie spät ist es?", "/viː ʃpɛːt ɪst ɛs/", "几点", "What time is it?", "time",
     "Entschuldigung, wie spät ist es?", None,
     "请问，现在几点？", "Excuse me, what time is it?"),

    ("Vater", "/ˈfaːtɐ/", "父亲", "Father", "family",
     "Mein Vater ist Lehrer.", None,
     "我父亲是老师。", "My father is a teacher."),
    ("Mutter", "/ˈmʊtɐ/", "母亲", "Mother", "family",
     "Meine Mutter kocht gut.", None,
     "我母亲厨艺很好。", "My mother cooks well."),
    ("Freund", "/fʁɔʏnt/", "朋友", "Friend", "family",
     "Er ist mein bester Freund.", None,
     "他是我最好的朋友。", "He's my best friend."),
    ("Bruder", "/ˈbʁuːdɐ/", "兄弟", "Brother", "family",
     "Mein Bruder wohnt in Berlin.", None,
     "我哥哥住在柏林。", "My brother lives in Berlin."),
    ("Schwester", "/ˈʃvɛstɐ/", "姐妹", "Sister", "family",
     "Meine Schwester ist Ärztin.", None,
     "我姐姐是医生。", "My sister is a doctor."),

    ("Brot", "/bʁoːt/", "面包", "Bread", "food",
     "Ich kaufe täglich frisches Brot.", None,
     "我每天买新鲜面包。", "I buy fresh bread daily."),
    ("Wurst", "/vʊʁst/", "香肠", "Sausage", "food",
     "Die Bratwurst ist typisch deutsch.", None,
     "烤香肠是德国特色。", "Bratwurst is typically German."),
    ("Käse", "/ˈkɛːzə/", "奶酪", "Cheese", "food",
     "Käse mit Wein schmeckt gut.", None,
     "奶酪配酒很美味。", "Cheese with wine is delicious."),
    ("Bier", "/biːɐ/", "啤酒", "Beer", "food",
     "Ein großes Bier, bitte.", None,
     "请来一大杯啤酒。", "A large beer, please."),
    ("Wasser", "/ˈvasɐ/", "水", "Water", "food",
     "Ein Glas Wasser, bitte.", None,
     "请给我一杯水。", "A glass of water, please."),
    ("Kaffee", "/ˈkafe/", "咖啡", "Coffee", "food",
     "Kaffee ohne Zucker, bitte.", None,
     "不加糖的咖啡，谢谢。", "Coffee without sugar, please."),
    ("Lecker", "/ˈlɛkɐ/", "好吃", "Tasty", "food",
     "Das Essen ist wirklich lecker!", None,
     "这菜真好吃！", "The food is really tasty!"),
    ("Ich habe Hunger", "/ɪç ˈhaːbə ˈhʊŋɐ/", "我饿了", "I'm hungry", "food",
     "Ich habe großen Hunger.", None,
     "我很饿。", "I'm very hungry."),
    ("Speisekarte", "/ˈʃpaɪzəkaʁtə/", "菜单", "Menu", "food",
     "Die Speisekarte, bitte.", None,
     "请给我菜单。", "The menu, please."),

    ("Wo ist...?", "/voː ɪst/", "在哪里", "Where is?", "travel",
     "Wo ist der Bahnhof?", None,
     "火车站在哪？", "Where is the station?"),
    ("Flughafen", "/ˈfluːkhaːfn̩/", "机场", "Airport", "travel",
     "Zum Flughafen, bitte.", None,
     "请去机场。", "To the airport, please."),
    ("Bahnhof", "/ˈbaːnhoːf/", "火车站", "Train station", "travel",
     "Der Bahnhof ist gleich um die Ecke.", None,
     "火车站就在拐角处。", "The station is right around the corner."),
    ("Hotel", "/hoˈtɛl/", "酒店", "Hotel", "travel",
     "Mein Hotel ist im Zentrum.", None,
     "我住市中心的酒店。", "My hotel is in the center."),
    ("Links", "/lɪŋks/", "左", "Left", "travel",
     "An der Ampel links abbiegen.", None,
     "在红绿灯左转。", "Turn left at the light."),
    ("Rechts", "/ʁɛçts/", "右", "Right", "travel",
     "Das Klo ist rechts.", None,
     "厕所在右边。", "The toilet is on the right."),

    ("Wie viel?", "/viː fiːl/", "多少钱", "How much?", "shopping",
     "Wie viel kostet das?", None,
     "这个多少钱？", "How much is this?"),
    ("Zu teuer", "/tsuː ˈtɔʏɐ/", "太贵", "Too expensive", "shopping",
     "Das ist zu teuer für mich.", None,
     "对我来说太贵了。", "That's too expensive for me."),

    ("Hilfe!", "/ˈhɪlfə/", "救命", "Help!", "emergency",
     "Hilfe! Rufen Sie die Polizei!", None,
     "救命！请叫警察！", "Help! Call the police!"),
    ("Arzt", "/aːɐtst/", "医生", "Doctor", "emergency",
     "Ich brauche einen Arzt.", None,
     "我需要医生。", "I need a doctor."),
    ("Krankenhaus", "/ˈkʁaŋkənhaʊs/", "医院", "Hospital", "emergency",
     "Wo ist das nächste Krankenhaus?", None,
     "最近的医院在哪？", "Where's the nearest hospital?"),

    ("Glücklich", "/ˈɡlʏklɪç/", "开心", "Happy", "feelings",
     "Ich bin glücklich, dich zu sehen.", None,
     "见到你我很开心。", "I'm happy to see you."),
    ("Müde", "/ˈmyːdə/", "累", "Tired", "feelings",
     "Ich bin sehr müde heute.", None,
     "我今天很累。", "I'm very tired today."),
    ("Ich liebe dich", "/ɪç ˈliːbə dɪç/", "我爱你", "I love you", "feelings",
     "Ich liebe dich für immer.", None,
     "我永远爱你。", "I'll love you forever."),

    ("Viel Glück", "/fiːl ɡlʏk/", "好运", "Good luck", "phrases",
     "Viel Glück bei der Prüfung!", None,
     "考试加油！", "Good luck on the exam!"),
    ("Kein Problem", "/kaɪn pʁoˈbleːm/", "没问题", "No problem", "phrases",
     "Kein Problem, ich mache das.", None,
     "没问题，我来做。", "No problem, I'll do it."),
    ("Guten Appetit", "/ˈɡuːtn̩ a.peˈtiːt/", "祝用餐愉快", "Enjoy your meal", "phrases",
     "Guten Appetit allen!", None,
     "大家请慢用！", "Enjoy your meal, everyone!"),
    ("Prost!", "/pʁoːst/", "干杯", "Cheers!", "phrases",
     "Prost auf unsere Freundschaft!", None,
     "为我们的友谊干杯！", "Cheers to our friendship!"),
    ("Ich verstehe nicht", "/ɪç fɛɐˈʃteːə nɪçt/", "我不明白", "I don't understand", "phrases",
     "Entschuldigung, ich verstehe nicht.", None,
     "抱歉，我没听懂。", "Sorry, I don't understand."),
    ("Noch einmal, bitte", "/nɔx ˈaɪnmaːl ˈbɪtə/", "请再说一遍", "Once more, please", "phrases",
     "Noch einmal, bitte, ich habe es nicht gehört.", None,
     "请再说一遍，我没听清。", "Once more please, I didn't hear."),
    ("Langsamer, bitte", "/ˈlaŋzaːmɐ ˈbɪtə/", "请慢点", "Slower please", "phrases",
     "Sprich bitte langsamer.", None,
     "请说慢点。", "Please speak slower."),
    ("Wie heißen Sie?", "/viː ˈhaɪsn̩ ziː/", "您叫什么名字", "What's your name?", "phrases",
     "Guten Tag, wie heißen Sie?", None,
     "您好，请问您叫什么？", "Good day, what's your name?"),
]
