# English 英语 — curated core vocab with IPA + example sentences.
VOCAB = [
    # greetings
    ("Hello", "/həˈloʊ/", "问候", "Hello", "greetings",
     "Hello! How are you today?", None,
     "你好！你今天好吗？", "Hello! How are you today?"),
    ("Hi", "/haɪ/", "非正式问候", "Hi (informal)", "greetings",
     "Hi there, long time no see!", None,
     "嗨，好久不见！", "Hi there, long time no see!"),
    ("Good morning", "/ɡʊd ˈmɔːrnɪŋ/", "早安", "Good morning", "greetings",
     "Good morning! Did you sleep well?", None,
     "早上好！睡得好吗？", "Good morning! Did you sleep well?"),
    ("Good evening", "/ɡʊd ˈiːvnɪŋ/", "晚安", "Good evening", "greetings",
     "Good evening, welcome to our restaurant.", None,
     "晚上好，欢迎光临本餐厅。", "Good evening, welcome to our restaurant."),
    ("How are you?", "/haʊ ɑːr juː/", "问近况", "How are you?", "greetings",
     "How are you? I haven't seen you in ages.", None,
     "你怎么样？好久没见到你了。", "How are you? I haven't seen you in ages."),
    ("Thank you", "/θæŋk juː/", "致谢", "Thank you", "greetings",
     "Thank you so much for your help.", None,
     "非常感谢你的帮助。", "Thank you so much for your help."),
    ("You're welcome", "/jʊr ˈwɛlkəm/", "回应感谢", "You're welcome", "greetings",
     "You're welcome, happy to help.", None,
     "不客气，很高兴能帮忙。", "You're welcome, happy to help."),
    ("Sorry", "/ˈsɒri/", "道歉", "Sorry", "greetings",
     "Sorry, I didn't mean to interrupt.", None,
     "抱歉，我不是故意打断你。", "Sorry, I didn't mean to interrupt."),
    ("It's okay", "/ɪts oʊˈkeɪ/", "没关系", "It's okay", "greetings",
     "It's okay, don't worry about it.", None,
     "没关系，别担心。", "It's okay, don't worry about it."),
    ("Goodbye", "/ɡʊdˈbaɪ/", "道别", "Goodbye", "greetings",
     "Goodbye, see you tomorrow!", None,
     "再见，明天见！", "Goodbye, see you tomorrow!"),

    # numbers
    ("One", "/wʌn/", "1", "One", "numbers",
     "I only have one question.", None,
     "我只有一个问题。", "I only have one question."),
    ("Two", "/tuː/", "2", "Two", "numbers",
     "Two coffees, please.", None,
     "两杯咖啡，谢谢。", "Two coffees, please."),
    ("Three", "/θriː/", "3", "Three", "numbers",
     "I'll be back in three hours.", None,
     "我三个小时后回来。", "I'll be back in three hours."),
    ("Four", "/fɔːr/", "4", "Four", "numbers",
     "A table for four, please.", None,
     "请准备四人桌。", "A table for four, please."),
    ("Five", "/faɪv/", "5", "Five", "numbers",
     "The meeting is at five.", None,
     "会议在五点。", "The meeting is at five."),
    ("Ten", "/tɛn/", "10", "Ten", "numbers",
     "It's ten past nine.", None,
     "现在是九点十分。", "It's ten past nine."),
    ("Hundred", "/ˈhʌndrəd/", "100", "One hundred", "numbers",
     "The ticket costs one hundred dollars.", None,
     "票要一百美元。", "The ticket costs one hundred dollars."),
    ("Thousand", "/ˈθaʊzənd/", "1000", "Thousand", "numbers",
     "There are a thousand ways to say hello.", None,
     "问候的方式有上千种。", "There are a thousand ways to say hello."),

    # time
    ("Today", "/təˈdeɪ/", "今日", "Today", "time",
     "Today is my birthday.", None,
     "今天是我生日。", "Today is my birthday."),
    ("Tomorrow", "/təˈmɒroʊ/", "明日", "Tomorrow", "time",
     "See you tomorrow!", None,
     "明天见！", "See you tomorrow!"),
    ("Yesterday", "/ˈjɛstərdeɪ/", "昨日", "Yesterday", "time",
     "I met her yesterday.", None,
     "我昨天见过她。", "I met her yesterday."),
    ("Now", "/naʊ/", "现在", "Now", "time",
     "We need to leave now.", None,
     "我们现在就得走了。", "We need to leave now."),
    ("Morning", "/ˈmɔːrnɪŋ/", "早晨", "Morning", "time",
     "I work out every morning.", None,
     "我每天早上健身。", "I work out every morning."),
    ("Evening", "/ˈiːvnɪŋ/", "傍晚", "Evening", "time",
     "Let's talk in the evening.", None,
     "我们晚上再聊。", "Let's talk in the evening."),
    ("What time is it?", "/wʌt taɪm ɪz ɪt/", "问时间", "What time is it?", "time",
     "Excuse me, what time is it?", None,
     "请问现在几点？", "Excuse me, what time is it?"),
    ("Wait a moment", "/weɪt ə ˈmoʊmənt/", "稍等", "Wait a moment", "time",
     "Wait a moment, I'll check.", None,
     "稍等一下，我查查看。", "Wait a moment, I'll check."),
    ("Week", "/wiːk/", "周", "Week", "time",
     "I'll see you next week.", None,
     "下周见。", "I'll see you next week."),
    ("Month", "/mʌnθ/", "月", "Month", "time",
     "This month has been busy.", None,
     "这个月很忙。", "This month has been busy."),

    # family
    ("Dad", "/dæd/", "爸爸", "Dad", "family",
     "My dad loves gardening.", None,
     "我爸爸喜欢园艺。", "My dad loves gardening."),
    ("Mom", "/mɒm/", "妈妈", "Mom", "family",
     "Mom is cooking dinner.", None,
     "妈妈在做晚饭。", "Mom is cooking dinner."),
    ("Brother", "/ˈbrʌðər/", "兄弟", "Brother", "family",
     "My brother lives in Canada.", None,
     "我哥哥住在加拿大。", "My brother lives in Canada."),
    ("Sister", "/ˈsɪstər/", "姐妹", "Sister", "family",
     "I have two sisters.", None,
     "我有两个姐妹。", "I have two sisters."),
    ("Friend", "/frɛnd/", "朋友", "Friend", "family",
     "She's my best friend.", None,
     "她是我最好的朋友。", "She's my best friend."),
    ("Child", "/tʃaɪld/", "小孩", "Child", "family",
     "The child is playing outside.", None,
     "那个小孩在外面玩。", "The child is playing outside."),
    ("Husband", "/ˈhʌzbənd/", "丈夫", "Husband", "family",
     "My husband works from home.", None,
     "我丈夫在家工作。", "My husband works from home."),
    ("Wife", "/waɪf/", "妻子", "Wife", "family",
     "His wife is a teacher.", None,
     "他妻子是老师。", "His wife is a teacher."),

    # food
    ("Rice", "/raɪs/", "米饭", "Rice", "food",
     "Would you like some rice?", None,
     "你要点米饭吗？", "Would you like some rice?"),
    ("Bread", "/brɛd/", "面包", "Bread", "food",
     "I usually have bread for breakfast.", None,
     "我早餐通常吃面包。", "I usually have bread for breakfast."),
    ("Noodles", "/ˈnuːdlz/", "面条", "Noodles", "food",
     "These noodles are delicious.", None,
     "这个面条真好吃。", "These noodles are delicious."),
    ("Meat", "/miːt/", "肉", "Meat", "food",
     "I don't eat much meat.", None,
     "我不怎么吃肉。", "I don't eat much meat."),
    ("Fish", "/fɪʃ/", "鱼", "Fish", "food",
     "Fish is good for your health.", None,
     "鱼对健康有益。", "Fish is good for your health."),
    ("Fruit", "/fruːt/", "水果", "Fruit", "food",
     "I eat fruit every day.", None,
     "我每天吃水果。", "I eat fruit every day."),
    ("Tea", "/tiː/", "茶", "Tea", "food",
     "Would you like a cup of tea?", None,
     "你要喝杯茶吗？", "Would you like a cup of tea?"),
    ("Water", "/ˈwɔːtər/", "水", "Water", "food",
     "Could I have some water, please?", None,
     "能给我点水吗？", "Could I have some water, please?"),
    ("Coffee", "/ˈkɒfi/", "咖啡", "Coffee", "food",
     "I can't start my day without coffee.", None,
     "没有咖啡我一天没法开始。", "I can't start my day without coffee."),
    ("Beer", "/bɪr/", "啤酒", "Beer", "food",
     "Two beers, please.", None,
     "两瓶啤酒，谢谢。", "Two beers, please."),
    ("Delicious", "/dɪˈlɪʃəs/", "美味的", "Delicious", "food",
     "This dessert is absolutely delicious!", None,
     "这甜点真是太好吃了！", "This dessert is absolutely delicious!"),
    ("I'm hungry", "/aɪm ˈhʌŋɡri/", "我饿了", "I'm hungry", "food",
     "I'm hungry, what's for dinner?", None,
     "我饿了，晚饭吃什么？", "I'm hungry, what's for dinner?"),
    ("Menu", "/ˈmɛnjuː/", "菜单", "Menu", "food",
     "Could we see the menu, please?", None,
     "请给我们看一下菜单。", "Could we see the menu, please?"),

    # colors
    ("Red", "/rɛd/", "红色", "Red", "colors",
     "I love red roses.", None,
     "我喜欢红玫瑰。", "I love red roses."),
    ("Blue", "/bluː/", "蓝色", "Blue", "colors",
     "The sky is blue today.", None,
     "今天天空是蓝色的。", "The sky is blue today."),
    ("Green", "/ɡriːn/", "绿色", "Green", "colors",
     "The grass is very green after the rain.", None,
     "雨后草坪非常绿。", "The grass is very green after the rain."),
    ("Yellow", "/ˈjɛloʊ/", "黄色", "Yellow", "colors",
     "Yellow is a cheerful color.", None,
     "黄色是明快的颜色。", "Yellow is a cheerful color."),
    ("Black", "/blæk/", "黑色", "Black", "colors",
     "She wore a black dress to the party.", None,
     "她穿了一件黑色礼服去派对。", "She wore a black dress to the party."),
    ("White", "/waɪt/", "白色", "White", "colors",
     "I'd like a white t-shirt.", None,
     "我想要一件白色 T 恤。", "I'd like a white t-shirt."),

    # body
    ("Head", "/hɛd/", "头", "Head", "body",
     "I have a terrible headache.", None,
     "我头很痛。", "I have a terrible headache."),
    ("Eye", "/aɪ/", "眼睛", "Eye", "body",
     "She has beautiful blue eyes.", None,
     "她有一双漂亮的蓝眼睛。", "She has beautiful blue eyes."),
    ("Hand", "/hænd/", "手", "Hand", "body",
     "Wash your hands before eating.", None,
     "吃饭前洗手。", "Wash your hands before eating."),
    ("Foot", "/fʊt/", "脚", "Foot", "body",
     "My feet hurt after walking all day.", None,
     "走了一天，脚很痛。", "My feet hurt after walking all day."),
    ("Heart", "/hɑːrt/", "心脏", "Heart", "body",
     "Running is good for your heart.", None,
     "跑步对心脏好。", "Running is good for your heart."),

    # weather
    ("Weather", "/ˈwɛðər/", "天气", "Weather", "weather",
     "The weather is lovely today.", None,
     "今天天气真好。", "The weather is lovely today."),
    ("Rain", "/reɪn/", "雨", "Rain", "weather",
     "It's going to rain tomorrow.", None,
     "明天会下雨。", "It's going to rain tomorrow."),
    ("Snow", "/snoʊ/", "雪", "Snow", "weather",
     "We had a lot of snow last winter.", None,
     "去年冬天下了很多雪。", "We had a lot of snow last winter."),
    ("Sunny", "/ˈsʌni/", "晴朗", "Sunny", "weather",
     "It's a beautiful sunny day.", None,
     "今天是美好的晴天。", "It's a beautiful sunny day."),
    ("Wind", "/wɪnd/", "风", "Wind", "weather",
     "The wind is strong tonight.", None,
     "今晚风很大。", "The wind is strong tonight."),

    # travel
    ("Where is...?", "/wɛr ɪz/", "询问位置", "Where is...?", "travel",
     "Where is the nearest subway station?", None,
     "最近的地铁站在哪里？", "Where is the nearest subway station?"),
    ("How do I get to...?", "/haʊ duː aɪ ɡɛt tuː/", "询问路线", "How do I get to...?", "travel",
     "How do I get to the airport from here?", None,
     "从这里怎么到机场？", "How do I get to the airport from here?"),
    ("Airport", "/ˈɛrpɔːrt/", "机场", "Airport", "travel",
     "I need to be at the airport by 3pm.", None,
     "我下午三点前要到机场。", "I need to be at the airport by 3pm."),
    ("Train station", "/treɪn ˈsteɪʃən/", "火车站", "Train station", "travel",
     "The train station is just around the corner.", None,
     "火车站就在拐角处。", "The train station is just around the corner."),
    ("Hotel", "/hoʊˈtɛl/", "酒店", "Hotel", "travel",
     "We're staying at a hotel near the beach.", None,
     "我们住在海边的酒店。", "We're staying at a hotel near the beach."),
    ("Ticket", "/ˈtɪkɪt/", "票", "Ticket", "travel",
     "Can I buy a ticket online?", None,
     "我可以在网上买票吗？", "Can I buy a ticket online?"),
    ("Left", "/lɛft/", "左", "Left", "travel",
     "Take the second left after the bridge.", None,
     "过桥后第二个左转。", "Take the second left after the bridge."),
    ("Right", "/raɪt/", "右", "Right", "travel",
     "The bathroom is on the right.", None,
     "卫生间在右边。", "The bathroom is on the right."),
    ("Go straight", "/ɡoʊ streɪt/", "直走", "Go straight", "travel",
     "Go straight for two blocks.", None,
     "直走两个街区。", "Go straight for two blocks."),
    ("Stop", "/stɒp/", "停", "Stop", "travel",
     "Please stop at the next corner.", None,
     "请在下个拐角停车。", "Please stop at the next corner."),

    # shopping
    ("How much?", "/haʊ mʌtʃ/", "多少钱", "How much?", "shopping",
     "How much does this cost?", None,
     "这个多少钱？", "How much does this cost?"),
    ("Too expensive", "/tuː ɪkˈspɛnsɪv/", "太贵", "Too expensive", "shopping",
     "That's too expensive, do you have anything cheaper?", None,
     "太贵了，有便宜点的吗？", "That's too expensive, do you have anything cheaper?"),
    ("Cheap", "/tʃiːp/", "便宜", "Cheap", "shopping",
     "This shop has cheap prices.", None,
     "这家店价格便宜。", "This shop has cheap prices."),
    ("I'll take this", "/aɪl teɪk ðɪs/", "要这个", "I'll take this", "shopping",
     "I'll take this one, please.", None,
     "我要这个，谢谢。", "I'll take this one, please."),
    ("Credit card", "/ˈkrɛdɪt kɑːrd/", "信用卡", "Credit card", "shopping",
     "Do you accept credit card?", None,
     "可以刷信用卡吗？", "Do you accept credit card?"),
    ("Receipt", "/rɪˈsiːt/", "收据", "Receipt", "shopping",
     "Could I have the receipt, please?", None,
     "请给我收据。", "Could I have the receipt, please?"),

    # emergency
    ("Help!", "/hɛlp/", "救命", "Help!", "emergency",
     "Help! Someone stole my bag!", None,
     "救命！有人偷了我的包！", "Help! Someone stole my bag!"),
    ("Police", "/pəˈliːs/", "警察", "Police", "emergency",
     "Please call the police.", None,
     "请叫警察。", "Please call the police."),
    ("Doctor", "/ˈdɒktər/", "医生", "Doctor", "emergency",
     "I need to see a doctor.", None,
     "我需要看医生。", "I need to see a doctor."),
    ("Hospital", "/ˈhɒspɪtl/", "医院", "Hospital", "emergency",
     "Where's the nearest hospital?", None,
     "最近的医院在哪里？", "Where's the nearest hospital?"),
    ("I'm lost", "/aɪm lɒst/", "迷路", "I'm lost", "emergency",
     "Excuse me, I'm lost. Can you help?", None,
     "不好意思，我迷路了。能帮我吗？", "Excuse me, I'm lost. Can you help?"),
    ("Call 911", "/kɔːl naɪn wʌn wʌn/", "叫急救", "Call 911", "emergency",
     "Call 911, this is an emergency!", None,
     "快打 911，这是紧急情况！", "Call 911, this is an emergency!"),

    # feelings
    ("Happy", "/ˈhæpi/", "快乐", "Happy", "feelings",
     "I'm so happy to see you!", None,
     "见到你我真高兴！", "I'm so happy to see you!"),
    ("Sad", "/sæd/", "悲伤", "Sad", "feelings",
     "She looked sad when she heard the news.", None,
     "听到消息时她看起来很悲伤。", "She looked sad when she heard the news."),
    ("Tired", "/ˈtaɪərd/", "疲倦", "Tired", "feelings",
     "I'm really tired, I need to rest.", None,
     "我太累了，得休息一下。", "I'm really tired, I need to rest."),
    ("Angry", "/ˈæŋɡri/", "生气", "Angry", "feelings",
     "Don't be angry, it was just a joke.", None,
     "别生气，只是个玩笑。", "Don't be angry, it was just a joke."),
    ("Scared", "/skɛrd/", "害怕", "Scared", "feelings",
     "I was scared of the dark as a child.", None,
     "小时候我怕黑。", "I was scared of the dark as a child."),
    ("I love you", "/aɪ lʌv juː/", "我爱你", "I love you", "feelings",
     "I love you more than anything.", None,
     "我爱你胜过一切。", "I love you more than anything."),
    ("I miss you", "/aɪ mɪs juː/", "想你", "I miss you", "feelings",
     "I miss you. When will you come back?", None,
     "我想你，你什么时候回来？", "I miss you. When will you come back?"),

    # verbs
    ("Eat", "/iːt/", "吃", "Eat", "verbs",
     "Let's eat together.", None,
     "我们一起吃饭吧。", "Let's eat together."),
    ("Drink", "/drɪŋk/", "喝", "Drink", "verbs",
     "I don't drink coffee at night.", None,
     "我晚上不喝咖啡。", "I don't drink coffee at night."),
    ("Go", "/ɡoʊ/", "去", "Go", "verbs",
     "Where do you want to go today?", None,
     "你今天想去哪儿？", "Where do you want to go today?"),
    ("Come", "/kʌm/", "来", "Come", "verbs",
     "Come over for dinner tonight.", None,
     "今晚过来吃饭吧。", "Come over for dinner tonight."),
    ("See", "/siː/", "看见", "See", "verbs",
     "I can see the mountains from my window.", None,
     "我从窗户能看到山。", "I can see the mountains from my window."),
    ("Hear", "/hɪr/", "听到", "Hear", "verbs",
     "Did you hear what she said?", None,
     "你听到她说的了吗？", "Did you hear what she said?"),
    ("Speak", "/spiːk/", "说", "Speak", "verbs",
     "Do you speak English?", None,
     "你会说英语吗？", "Do you speak English?"),
    ("Read", "/riːd/", "读", "Read", "verbs",
     "I read a book every week.", None,
     "我每周读一本书。", "I read a book every week."),
    ("Write", "/raɪt/", "写", "Write", "verbs",
     "She writes for a magazine.", None,
     "她为一本杂志写稿。", "She writes for a magazine."),
    ("Learn", "/lɜːrn/", "学习", "Learn", "verbs",
     "I'm learning Chinese this year.", None,
     "我今年在学中文。", "I'm learning Chinese this year."),
    ("Work", "/wɜːrk/", "工作", "Work", "verbs",
     "I work from 9 to 5.", None,
     "我朝九晚五上班。", "I work from 9 to 5."),
    ("Sleep", "/sliːp/", "睡觉", "Sleep", "verbs",
     "I need to sleep more.", None,
     "我得多睡点觉。", "I need to sleep more."),

    # adjectives
    ("Big", "/bɪɡ/", "大", "Big", "adjectives",
     "That's a big decision.", None,
     "那是一个重大决定。", "That's a big decision."),
    ("Small", "/smɔːl/", "小", "Small", "adjectives",
     "I'd like a small coffee, please.", None,
     "请来一杯小杯咖啡。", "I'd like a small coffee, please."),
    ("Good", "/ɡʊd/", "好的", "Good", "adjectives",
     "That's a good idea!", None,
     "那是个好主意！", "That's a good idea!"),
    ("Bad", "/bæd/", "坏的", "Bad", "adjectives",
     "I had a really bad day.", None,
     "我今天过得很糟糕。", "I had a really bad day."),
    ("Fast", "/fæst/", "快", "Fast", "adjectives",
     "He's a fast runner.", None,
     "他跑得很快。", "He's a fast runner."),
    ("Slow", "/sloʊ/", "慢", "Slow", "adjectives",
     "The internet is really slow today.", None,
     "今天网速很慢。", "The internet is really slow today."),

    # phrases
    ("How's it going?", "/haʊz ɪt ˈɡoʊɪŋ/", "近况如何", "How's it going?", "phrases",
     "Hey, how's it going?", None,
     "嘿，最近怎么样？", "Hey, how's it going?"),
    ("No worries", "/noʊ ˈwʌriz/", "没事", "No worries", "phrases",
     "No worries, I can wait.", None,
     "没关系，我可以等。", "No worries, I can wait."),
    ("Never mind", "/ˈnɛvər maɪnd/", "算了", "Never mind", "phrases",
     "Never mind, I'll figure it out.", None,
     "算了，我自己想办法。", "Never mind, I'll figure it out."),
    ("Excuse me", "/ɪkˈskjuːz miː/", "打扰", "Excuse me", "phrases",
     "Excuse me, could you move over a bit?", None,
     "不好意思，您能挪一下吗？", "Excuse me, could you move over a bit?"),
    ("I don't understand", "/aɪ doʊnt ˌʌndərˈstænd/", "不明白", "I don't understand", "phrases",
     "Sorry, I don't understand. Could you repeat that?", None,
     "抱歉，我没听懂，能再说一遍吗？", "Sorry, I don't understand. Could you repeat that?"),
    ("Speak slowly", "/spiːk ˈsloʊli/", "慢点说", "Speak slowly please", "phrases",
     "Could you speak slowly please?", None,
     "能请你说慢一点吗？", "Could you speak slowly please?"),
    ("What's your name?", "/wʌts jʊr neɪm/", "问姓名", "What's your name?", "phrases",
     "Hi, I'm Alex. What's your name?", None,
     "嗨，我叫 Alex。你叫什么名字？", "Hi, I'm Alex. What's your name?"),
    ("Nice to meet you", "/naɪs tuː miːt juː/", "客套", "Nice to meet you", "phrases",
     "Nice to meet you! I've heard so much about you.", None,
     "很高兴认识你！我听说过很多关于你的事。", "Nice to meet you! I've heard so much about you."),
    ("Let's go!", "/lɛts ɡoʊ/", "走吧", "Let's go!", "phrases",
     "Everyone ready? Let's go!", None,
     "大家都准备好了吗？出发！", "Everyone ready? Let's go!"),
    ("Take care", "/teɪk kɛr/", "保重", "Take care", "phrases",
     "Take care, and call me when you arrive.", None,
     "保重，到了打电话给我。", "Take care, and call me when you arrive."),
]
