# Spanish 西班牙语 — curated core vocab with IPA + example sentences.
VOCAB = [
    ("Hola", "/ˈo.la/", "你好", "Hello", "greetings",
     "¡Hola! ¿Cómo estás?", None,
     "你好！你好吗？", "Hi! How are you?"),
    ("Buenos días", "/ˈbwe.nos ˈdi.as/", "早上好", "Good morning", "greetings",
     "Buenos días, ¿has dormido bien?", None,
     "早上好，睡得好吗？", "Good morning, did you sleep well?"),
    ("Buenas noches", "/ˈbwe.nas ˈno.tʃes/", "晚上好／晚安", "Good evening / night", "greetings",
     "Buenas noches, hasta mañana.", None,
     "晚安，明天见。", "Good night, see you tomorrow."),
    ("Gracias", "/ˈɡɾa.θjas/", "谢谢", "Thank you", "greetings",
     "Muchas gracias por tu ayuda.", None,
     "非常感谢你的帮助。", "Thank you so much for your help."),
    ("De nada", "/de ˈna.ða/", "不客气", "You're welcome", "greetings",
     "De nada, para eso están los amigos.", None,
     "不客气，朋友就是要互相帮忙。", "You're welcome, that's what friends are for."),
    ("Lo siento", "/lo ˈsjen.to/", "对不起", "Sorry", "greetings",
     "Lo siento mucho, no fue mi intención.", None,
     "我很抱歉，不是故意的。", "I'm so sorry, I didn't mean to."),
    ("Está bien", "/esˈta bjen/", "没关系", "It's okay", "greetings",
     "Está bien, no te preocupes.", None,
     "没关系，别担心。", "It's okay, don't worry."),
    ("Adiós", "/aˈðjos/", "再见", "Goodbye", "greetings",
     "Adiós, ¡hasta pronto!", None,
     "再见，回头见！", "Bye, see you soon!"),

    ("Uno", "/ˈu.no/", "1", "One", "numbers",
     "Solo necesito uno.", None,
     "我只需要一个。", "I just need one."),
    ("Dos", "/dos/", "2", "Two", "numbers",
     "Una mesa para dos, por favor.", None,
     "请来个两人桌。", "A table for two, please."),
    ("Tres", "/tɾes/", "3", "Three", "numbers",
     "Tengo tres hermanos.", None,
     "我有三个兄弟姐妹。", "I have three siblings."),
    ("Diez", "/djeθ/", "10", "Ten", "numbers",
     "Nos vemos en diez minutos.", None,
     "十分钟后见。", "See you in ten minutes."),

    ("Hoy", "/oi/", "今天", "Today", "time",
     "Hoy hace mucho calor.", None,
     "今天真热。", "It's very hot today."),
    ("Mañana", "/maˈɲa.na/", "明天／早晨", "Tomorrow / Morning", "time",
     "Mañana tengo una reunión.", None,
     "明天我有会议。", "I have a meeting tomorrow."),
    ("Ayer", "/aˈʝeɾ/", "昨天", "Yesterday", "time",
     "Ayer fui al cine.", None,
     "昨天我去看电影了。", "I went to the movies yesterday."),
    ("Ahora", "/aˈo.ɾa/", "现在", "Now", "time",
     "Tengo que irme ahora.", None,
     "我现在得走了。", "I have to go now."),
    ("¿Qué hora es?", "/ke ˈo.ɾa es/", "几点", "What time is it?", "time",
     "Perdón, ¿qué hora es?", None,
     "抱歉，现在几点？", "Sorry, what time is it?"),

    ("Papá", "/paˈpa/", "爸爸", "Dad", "family",
     "Mi papá es cocinero.", None,
     "我爸爸是厨师。", "My dad is a cook."),
    ("Mamá", "/maˈma/", "妈妈", "Mom", "family",
     "Mamá hace la mejor comida.", None,
     "妈妈做的饭最好吃。", "Mom makes the best food."),
    ("Amigo", "/aˈmi.ɣo/", "朋友", "Friend", "family",
     "Es mi mejor amigo.", None,
     "他是我最好的朋友。", "He's my best friend."),
    ("Hermano", "/eɾˈma.no/", "兄弟", "Brother", "family",
     "Mi hermano vive en Madrid.", None,
     "我哥哥住在马德里。", "My brother lives in Madrid."),
    ("Hermana", "/eɾˈma.na/", "姐妹", "Sister", "family",
     "Tengo una hermana menor.", None,
     "我有个妹妹。", "I have a younger sister."),

    ("Arroz", "/aˈroθ/", "米饭", "Rice", "food",
     "Me gusta el arroz con frijoles.", None,
     "我喜欢米饭配豆子。", "I like rice and beans."),
    ("Pan", "/pan/", "面包", "Bread", "food",
     "El pan aquí está delicioso.", None,
     "这里的面包很好吃。", "The bread here is delicious."),
    ("Paella", "/paˈeʎa/", "西班牙海鲜饭", "Paella", "food",
     "La paella valenciana es la mejor.", None,
     "瓦伦西亚海鲜饭最棒。", "Valencian paella is the best."),
    ("Agua", "/ˈa.ɣwa/", "水", "Water", "food",
     "Un vaso de agua, por favor.", None,
     "请来一杯水。", "A glass of water, please."),
    ("Café", "/kaˈfe/", "咖啡", "Coffee", "food",
     "Un café con leche, por favor.", None,
     "请来一杯咖啡拿铁。", "A coffee with milk, please."),
    ("Cerveza", "/θeɾˈβe.θa/", "啤酒", "Beer", "food",
     "Dos cervezas frías.", None,
     "两瓶冰啤酒。", "Two cold beers."),
    ("Delicioso", "/de.liˈθjo.so/", "好吃", "Delicious", "food",
     "¡Este postre está delicioso!", None,
     "这个甜点真好吃！", "This dessert is delicious!"),
    ("Tengo hambre", "/ˈteŋ.ɡo ˈam.bɾe/", "我饿了", "I'm hungry", "food",
     "Tengo hambre, ¿vamos a comer?", None,
     "我饿了，去吃饭吧？", "I'm hungry, shall we eat?"),

    ("¿Dónde está?", "/ˈdon.de esˈta/", "在哪里", "Where is?", "travel",
     "¿Dónde está la estación?", None,
     "车站在哪里？", "Where is the station?"),
    ("Aeropuerto", "/a.e.ɾoˈpweɾ.to/", "机场", "Airport", "travel",
     "Voy al aeropuerto en taxi.", None,
     "我坐出租车去机场。", "I'm taking a taxi to the airport."),
    ("Hotel", "/oˈtel/", "酒店", "Hotel", "travel",
     "Busco un hotel cerca del centro.", None,
     "我找市中心附近的酒店。", "I'm looking for a hotel near downtown."),
    ("Izquierda", "/iθˈkjeɾ.ða/", "左", "Left", "travel",
     "Gire a la izquierda en la esquina.", None,
     "在拐角左转。", "Turn left at the corner."),
    ("Derecha", "/deˈɾe.tʃa/", "右", "Right", "travel",
     "La tienda está a la derecha.", None,
     "商店在右边。", "The shop is on the right."),

    ("¿Cuánto cuesta?", "/ˈkwan.to ˈkwes.ta/", "多少钱", "How much?", "shopping",
     "¿Cuánto cuesta esta camisa?", None,
     "这件衬衫多少钱？", "How much is this shirt?"),
    ("Muy caro", "/mwi ˈka.ɾo/", "太贵", "Too expensive", "shopping",
     "Es muy caro, ¿tienes algo más barato?", None,
     "太贵了，有便宜点的吗？", "Too expensive, got something cheaper?"),

    ("¡Ayuda!", "/aˈʝu.ða/", "救命", "Help!", "emergency",
     "¡Ayuda! ¡Llamen a la policía!", None,
     "救命！快报警！", "Help! Call the police!"),
    ("Médico", "/ˈme.ði.ko/", "医生", "Doctor", "emergency",
     "Necesito un médico.", None,
     "我需要医生。", "I need a doctor."),
    ("Hospital", "/os.piˈtal/", "医院", "Hospital", "emergency",
     "¿Dónde está el hospital más cercano?", None,
     "最近的医院在哪？", "Where's the nearest hospital?"),
    ("Estoy perdido", "/esˈtoi peɾˈði.ðo/", "我迷路了", "I'm lost", "emergency",
     "Disculpe, estoy perdido, ¿puede ayudarme?", None,
     "抱歉我迷路了，能帮我吗？", "Excuse me, I'm lost, can you help?"),

    ("Feliz", "/feˈliθ/", "开心", "Happy", "feelings",
     "Estoy feliz de verte.", None,
     "见到你很开心。", "I'm happy to see you."),
    ("Cansado", "/kanˈsa.ðo/", "累", "Tired", "feelings",
     "Estoy muy cansado hoy.", None,
     "我今天很累。", "I'm very tired today."),
    ("Te quiero", "/te ˈkje.ɾo/", "我爱你（常用）", "I love you", "feelings",
     "Te quiero mucho.", None,
     "我很爱你。", "I love you a lot."),

    ("¡Buena suerte!", "/ˈbwe.na ˈsweɾ.te/", "好运", "Good luck!", "phrases",
     "¡Buena suerte en el examen!", None,
     "祝你考试顺利！", "Good luck on the exam!"),
    ("No hay problema", "/no ai pɾoˈβle.ma/", "没问题", "No problem", "phrases",
     "No hay problema, lo haré yo.", None,
     "没问题，我来做。", "No problem, I'll do it."),
    ("Buen provecho", "/bwen pɾoˈβe.tʃo/", "祝用餐愉快", "Enjoy your meal", "phrases",
     "¡Buen provecho a todos!", None,
     "大家用餐愉快！", "Enjoy your meal, everyone!"),
    ("¡Salud!", "/saˈluð/", "干杯／保重", "Cheers! / Bless you!", "phrases",
     "¡Salud por nuestros amigos!", None,
     "为我们的朋友干杯！", "Cheers to our friends!"),
    ("No entiendo", "/no enˈtjen.do/", "我不明白", "I don't understand", "phrases",
     "Perdón, no entiendo, ¿puede repetir?", None,
     "抱歉我不明白，能再说一遍吗？", "Sorry, I don't understand, could you repeat?"),
    ("Más despacio", "/mas desˈpa.θjo/", "请说慢点", "Slower please", "phrases",
     "Por favor, hable más despacio.", None,
     "请说慢点。", "Please speak slower."),
    ("¿Cómo te llamas?", "/ˈko.mo te ˈʝa.mas/", "你叫什么名字", "What's your name?", "phrases",
     "Hola, ¿cómo te llamas?", None,
     "你好，你叫什么名字？", "Hi, what's your name?"),
]
