# French 法语 — curated core vocab with IPA + example sentences.
VOCAB = [
    ("Bonjour", "/bɔ̃.ʒuʁ/", "你好（白天）", "Hello", "greetings",
     "Bonjour ! Comment allez-vous ?", None,
     "你好！您好吗？", "Hello! How are you?"),
    ("Bonsoir", "/bɔ̃.swaʁ/", "晚上好", "Good evening", "greetings",
     "Bonsoir, bienvenue chez nous.", None,
     "晚上好，欢迎光临。", "Good evening, welcome to our place."),
    ("Salut", "/sa.ly/", "嗨／再见（非正式）", "Hi / Bye (informal)", "greetings",
     "Salut ! Ça fait longtemps !", None,
     "嗨！好久不见！", "Hi! It's been a while!"),
    ("Merci", "/mɛʁ.si/", "谢谢", "Thank you", "greetings",
     "Merci beaucoup pour votre aide.", None,
     "非常感谢您的帮助。", "Thank you very much for your help."),
    ("De rien", "/də ʁjɛ̃/", "不客气", "You're welcome", "greetings",
     "De rien, c'est normal.", None,
     "不客气，应该的。", "You're welcome, it's nothing."),
    ("Pardon", "/paʁ.dɔ̃/", "对不起", "Sorry / Pardon", "greetings",
     "Pardon, je ne voulais pas vous déranger.", None,
     "抱歉，我不想打扰您。", "Sorry, I didn't mean to disturb you."),
    ("Au revoir", "/o ʁə.vwaʁ/", "再见", "Goodbye", "greetings",
     "Au revoir, à bientôt !", None,
     "再见，回头见！", "Goodbye, see you soon!"),
    ("Bonne nuit", "/bɔn nɥi/", "晚安", "Good night", "greetings",
     "Bonne nuit, fais de beaux rêves.", None,
     "晚安，做个好梦。", "Good night, sweet dreams."),

    ("Un", "/œ̃/", "1", "One", "numbers",
     "Je voudrais un café, s'il vous plaît.", None,
     "我要一杯咖啡。", "I'd like a coffee, please."),
    ("Deux", "/dø/", "2", "Two", "numbers",
     "Deux bières, s'il vous plaît.", None,
     "两杯啤酒，谢谢。", "Two beers, please."),
    ("Trois", "/tʁwa/", "3", "Three", "numbers",
     "J'ai trois enfants.", None,
     "我有三个孩子。", "I have three children."),
    ("Dix", "/dis/", "10", "Ten", "numbers",
     "On part dans dix minutes.", None,
     "我们十分钟后出发。", "We leave in ten minutes."),

    ("Aujourd'hui", "/o.ʒuʁ.dɥi/", "今天", "Today", "time",
     "Aujourd'hui, il fait beau.", None,
     "今天天气很好。", "The weather is nice today."),
    ("Demain", "/də.mɛ̃/", "明天", "Tomorrow", "time",
     "On se voit demain ?", None,
     "明天见吗？", "See you tomorrow?"),
    ("Hier", "/jɛʁ/", "昨天", "Yesterday", "time",
     "Hier, j'ai vu un bon film.", None,
     "昨天我看了一部好电影。", "Yesterday I saw a good movie."),
    ("Maintenant", "/mɛ̃t.nɑ̃/", "现在", "Now", "time",
     "Il faut partir maintenant.", None,
     "现在必须走了。", "We have to leave now."),
    ("Quelle heure est-il ?", "/kɛl‿œʁ ɛ til/", "几点", "What time is it?", "time",
     "Excusez-moi, quelle heure est-il ?", None,
     "请问，现在几点？", "Excuse me, what time is it?"),

    ("Papa", "/pa.pa/", "爸爸", "Dad", "family",
     "Papa travaille dans le jardin.", None,
     "爸爸在花园里劳作。", "Dad is working in the garden."),
    ("Maman", "/ma.mɑ̃/", "妈妈", "Mom", "family",
     "Maman prépare le dîner.", None,
     "妈妈在准备晚饭。", "Mom is preparing dinner."),
    ("Ami", "/a.mi/", "朋友", "Friend", "family",
     "C'est mon meilleur ami.", None,
     "他是我最好的朋友。", "He's my best friend."),
    ("Frère", "/fʁɛʁ/", "兄弟", "Brother", "family",
     "Mon frère habite à Paris.", None,
     "我哥哥住在巴黎。", "My brother lives in Paris."),
    ("Sœur", "/sœʁ/", "姐妹", "Sister", "family",
     "J'ai une petite sœur.", None,
     "我有个妹妹。", "I have a younger sister."),

    ("Pain", "/pɛ̃/", "面包", "Bread", "food",
     "Du pain frais, s'il vous plaît.", None,
     "要新鲜面包，谢谢。", "Fresh bread, please."),
    ("Fromage", "/fʁɔ.maʒ/", "奶酪", "Cheese", "food",
     "La France a plus de 400 fromages.", None,
     "法国有 400 多种奶酪。", "France has over 400 cheeses."),
    ("Croissant", "/kʁwa.sɑ̃/", "可颂", "Croissant", "food",
     "Un croissant et un café, s'il vous plaît.", None,
     "一个可颂和一杯咖啡。", "A croissant and a coffee, please."),
    ("Vin", "/vɛ̃/", "葡萄酒", "Wine", "food",
     "Du vin rouge pour moi.", None,
     "我要红葡萄酒。", "Red wine for me."),
    ("Eau", "/o/", "水", "Water", "food",
     "Une carafe d'eau, s'il vous plaît.", None,
     "请来一壶水。", "A carafe of water, please."),
    ("Café", "/ka.fe/", "咖啡", "Coffee", "food",
     "Un café serré, s'il vous plaît.", None,
     "一杯浓咖啡。", "A strong espresso, please."),
    ("Délicieux", "/de.li.sjø/", "好吃", "Delicious", "food",
     "Ce plat est vraiment délicieux !", None,
     "这道菜真好吃！", "This dish is really delicious!"),
    ("J'ai faim", "/ʒe fɛ̃/", "饿了", "I'm hungry", "food",
     "J'ai faim, on mange ?", None,
     "我饿了，我们吃饭吧？", "I'm hungry, shall we eat?"),

    ("Où est...?", "/u ɛ/", "在哪里", "Where is?", "travel",
     "Où est la gare, s'il vous plaît ?", None,
     "请问火车站在哪里？", "Where is the train station, please?"),
    ("Gare", "/ɡaʁ/", "火车站", "Train station", "travel",
     "On se retrouve à la gare.", None,
     "在火车站碰头。", "Let's meet at the station."),
    ("Aéroport", "/a.e.ʁɔ.pɔʁ/", "机场", "Airport", "travel",
     "L'aéroport est loin d'ici ?", None,
     "机场离这里远吗？", "Is the airport far from here?"),
    ("Hôtel", "/o.tɛl/", "酒店", "Hotel", "travel",
     "Je cherche un hôtel pas cher.", None,
     "我找便宜的酒店。", "I'm looking for a cheap hotel."),
    ("À gauche", "/a ɡoʃ/", "向左", "To the left", "travel",
     "Tournez à gauche au feu.", None,
     "在红绿灯左转。", "Turn left at the light."),
    ("À droite", "/a dʁwat/", "向右", "To the right", "travel",
     "La boulangerie est à droite.", None,
     "面包店在右边。", "The bakery is on the right."),

    ("Combien ?", "/kɔ̃.bjɛ̃/", "多少钱", "How much?", "shopping",
     "C'est combien ?", None,
     "多少钱？", "How much is it?"),
    ("Trop cher", "/tʁo ʃɛʁ/", "太贵", "Too expensive", "shopping",
     "C'est trop cher pour moi.", None,
     "对我来说太贵了。", "It's too expensive for me."),

    ("Au secours !", "/o sə.kuʁ/", "救命", "Help!", "emergency",
     "Au secours ! Appelez la police !", None,
     "救命！快报警！", "Help! Call the police!"),
    ("Médecin", "/med.sɛ̃/", "医生", "Doctor", "emergency",
     "Il me faut un médecin.", None,
     "我需要医生。", "I need a doctor."),
    ("Hôpital", "/o.pi.tal/", "医院", "Hospital", "emergency",
     "Où est l'hôpital le plus proche ?", None,
     "最近的医院在哪？", "Where's the nearest hospital?"),

    ("Heureux", "/ø.ʁø/", "开心", "Happy", "feelings",
     "Je suis heureux de te voir.", None,
     "见到你真开心。", "I'm happy to see you."),
    ("Fatigué", "/fa.ti.ɡe/", "累", "Tired", "feelings",
     "Je suis tellement fatigué.", None,
     "我好累。", "I'm so tired."),
    ("Je t'aime", "/ʒə tɛm/", "我爱你", "I love you", "feelings",
     "Je t'aime pour toujours.", None,
     "我永远爱你。", "I love you forever."),

    ("Bonne chance", "/bɔn ʃɑ̃s/", "好运", "Good luck", "phrases",
     "Bonne chance pour l'examen !", None,
     "考试顺利！", "Good luck on the exam!"),
    ("Pas de problème", "/pa də pʁɔ.blɛm/", "没问题", "No problem", "phrases",
     "Pas de problème, je comprends.", None,
     "没问题，我理解。", "No problem, I understand."),
    ("Bon appétit", "/bɔ.n‿a.pe.ti/", "祝用餐愉快", "Enjoy your meal", "phrases",
     "Bon appétit tout le monde !", None,
     "大家请慢用！", "Enjoy the meal, everyone!"),
    ("Santé !", "/sɑ̃.te/", "干杯", "Cheers!", "phrases",
     "Santé, à votre bonheur !", None,
     "干杯，祝您幸福！", "Cheers, to your happiness!"),
    ("Je ne comprends pas", "/ʒə nə kɔ̃.pʁɑ̃ pa/", "我不明白", "I don't understand", "phrases",
     "Désolé, je ne comprends pas, parlez plus lentement.", None,
     "抱歉，我不明白，请说慢点。", "Sorry, I don't understand, please speak slower."),
    ("Comment vous appelez-vous ?", "/kɔ.mɑ̃ vu z‿ap.le vu/", "您叫什么名字", "What's your name?", "phrases",
     "Enchanté, comment vous appelez-vous ?", None,
     "幸会，请问您叫什么？", "Nice to meet you, what's your name?"),
]
