# Japanese 日语 — curated core vocab with Romaji + example sentences.
VOCAB = [
    # greetings
    ("こんにちは", "konnichiwa", "你好／白天好", "Hello", "greetings",
     "こんにちは、お元気ですか？", "konnichiwa, ogenki desu ka?",
     "你好，你好吗？", "Hello, how are you?"),
    ("おはようございます", "ohayou gozaimasu", "早安（敬语）", "Good morning", "greetings",
     "おはようございます、今日もよろしくお願いします。", "ohayou gozaimasu, kyou mo yoroshiku onegaishimasu.",
     "早上好，今天也请多关照。", "Good morning, please look after me today as well."),
    ("こんばんは", "konbanwa", "晚上好", "Good evening", "greetings",
     "こんばんは、遅くなってすみません。", "konbanwa, osoku natte sumimasen.",
     "晚上好，抱歉来晚了。", "Good evening, sorry I'm late."),
    ("ありがとうございます", "arigatou gozaimasu", "谢谢（敬语）", "Thank you (polite)", "greetings",
     "助けてくれてありがとうございます。", "tasukete kurete arigatou gozaimasu.",
     "谢谢你帮我。", "Thank you for helping me."),
    ("すみません", "sumimasen", "对不起／劳驾", "Excuse me / Sorry", "greetings",
     "すみません、トイレはどこですか？", "sumimasen, toire wa doko desu ka?",
     "不好意思，请问洗手间在哪里？", "Excuse me, where's the restroom?"),
    ("大丈夫です", "daijoubu desu", "没关系／没事", "It's okay", "greetings",
     "大丈夫です、気にしないでください。", "daijoubu desu, ki ni shinaide kudasai.",
     "没关系，别在意。", "It's okay, don't worry about it."),
    ("さようなら", "sayounara", "再见", "Goodbye", "greetings",
     "それではさようなら、お元気で。", "sore dewa sayounara, ogenki de.",
     "那么再见，请保重。", "Goodbye then, take care."),
    ("おやすみなさい", "oyasuminasai", "晚安", "Good night", "greetings",
     "もう寝ます、おやすみなさい。", "mou nemasu, oyasuminasai.",
     "我要睡了，晚安。", "I'm going to sleep, good night."),

    # numbers
    ("一", "ichi", "1", "One", "numbers",
     "コーヒーを一つください。", "koohii wo hitotsu kudasai.",
     "请给我一杯咖啡。", "One coffee, please."),
    ("二", "ni", "2", "Two", "numbers",
     "二人です。", "futari desu.",
     "两位。", "Two people."),
    ("三", "san", "3", "Three", "numbers",
     "三時に会いましょう。", "san ji ni aimashou.",
     "三点见吧。", "Let's meet at three."),
    ("十", "juu", "10", "Ten", "numbers",
     "あと十分です。", "ato juppun desu.",
     "还有十分钟。", "Ten more minutes."),
    ("百", "hyaku", "100", "Hundred", "numbers",
     "百円で買えます。", "hyaku en de kaemasu.",
     "一百日元就能买到。", "You can buy it for 100 yen."),

    # time
    ("今日", "kyou", "今天", "Today", "time",
     "今日は忙しいです。", "kyou wa isogashii desu.",
     "今天很忙。", "Today is busy."),
    ("明日", "ashita", "明天", "Tomorrow", "time",
     "明日また来ます。", "ashita mata kimasu.",
     "明天再来。", "I'll come again tomorrow."),
    ("昨日", "kinou", "昨天", "Yesterday", "time",
     "昨日映画を見ました。", "kinou eiga wo mimashita.",
     "昨天看了电影。", "I watched a movie yesterday."),
    ("今", "ima", "现在", "Now", "time",
     "今、出発します。", "ima, shuppatsu shimasu.",
     "现在出发。", "I'm leaving now."),
    ("何時ですか", "nanji desu ka", "问时间", "What time?", "time",
     "すみません、今何時ですか？", "sumimasen, ima nanji desu ka?",
     "请问，现在几点？", "Excuse me, what time is it now?"),

    # family
    ("お父さん", "otousan", "爸爸（敬）", "Dad", "family",
     "お父さんはエンジニアです。", "otousan wa enjinia desu.",
     "爸爸是工程师。", "My dad is an engineer."),
    ("お母さん", "okaasan", "妈妈（敬）", "Mom", "family",
     "お母さんの料理が一番おいしい。", "okaasan no ryouri ga ichiban oishii.",
     "妈妈做的菜最好吃。", "Mom's cooking is the best."),
    ("友達", "tomodachi", "朋友", "Friend", "family",
     "友達と映画を見に行きます。", "tomodachi to eiga wo mi ni ikimasu.",
     "和朋友一起去看电影。", "I'm going to watch a movie with a friend."),
    ("家族", "kazoku", "家人", "Family", "family",
     "家族は四人です。", "kazoku wa yonin desu.",
     "家里有四口人。", "My family has four members."),

    # food
    ("ご飯", "gohan", "米饭／饭", "Rice / Meal", "food",
     "もうご飯食べましたか？", "mou gohan tabemashita ka?",
     "你吃饭了吗？", "Have you eaten yet?"),
    ("ラーメン", "raamen", "拉面", "Ramen", "food",
     "このラーメンは本当においしい！", "kono raamen wa hontou ni oishii!",
     "这拉面真的很好吃！", "This ramen is truly delicious!"),
    ("寿司", "sushi", "寿司", "Sushi", "food",
     "お寿司が食べたいです。", "osushi ga tabetai desu.",
     "想吃寿司。", "I want to eat sushi."),
    ("お茶", "ocha", "茶", "Tea", "food",
     "お茶をいかがですか？", "ocha wo ikaga desu ka?",
     "来点茶如何？", "Would you like some tea?"),
    ("水", "mizu", "水", "Water", "food",
     "お水を一杯ください。", "omizu wo ippai kudasai.",
     "请给我一杯水。", "A glass of water, please."),
    ("おいしい", "oishii", "好吃", "Delicious", "food",
     "この料理、すごくおいしいですね！", "kono ryouri, sugoku oishii desu ne!",
     "这道菜非常好吃呢！", "This dish is really delicious!"),
    ("メニュー", "menyuu", "菜单", "Menu", "food",
     "メニューを見せてください。", "menyuu wo misete kudasai.",
     "请给我看菜单。", "Please show me the menu."),

    # travel
    ("どこですか", "doko desu ka", "在哪里", "Where is?", "travel",
     "駅はどこですか？", "eki wa doko desu ka?",
     "车站在哪里？", "Where is the station?"),
    ("空港", "kuukou", "机场", "Airport", "travel",
     "空港まで一時間かかります。", "kuukou made ichi jikan kakarimasu.",
     "到机场要一个小时。", "It takes an hour to the airport."),
    ("駅", "eki", "车站", "Station", "travel",
     "駅の前で待ってます。", "eki no mae de mattemasu.",
     "我在车站前等你。", "I'll wait in front of the station."),
    ("ホテル", "hoteru", "酒店", "Hotel", "travel",
     "ホテルに泊まります。", "hoteru ni tomarimasu.",
     "我住在酒店。", "I'm staying at a hotel."),
    ("左", "hidari", "左", "Left", "travel",
     "次の角を左に曲がってください。", "tsugi no kado wo hidari ni magatte kudasai.",
     "请在下个拐角左转。", "Please turn left at the next corner."),
    ("右", "migi", "右", "Right", "travel",
     "トイレは右側にあります。", "toire wa migi gawa ni arimasu.",
     "洗手间在右边。", "The restroom is on the right."),

    # shopping
    ("いくらですか", "ikura desu ka", "多少钱", "How much?", "shopping",
     "これはいくらですか？", "kore wa ikura desu ka?",
     "这个多少钱？", "How much is this?"),
    ("高いです", "takai desu", "贵", "Expensive", "shopping",
     "ちょっと高いですね。", "chotto takai desu ne.",
     "有点贵呢。", "It's a bit expensive."),
    ("これ", "kore", "这个", "This", "shopping",
     "これをください。", "kore wo kudasai.",
     "请给我这个。", "I'll take this."),

    # emergency
    ("助けて", "tasukete", "救命", "Help!", "emergency",
     "助けて！誰か！", "tasukete! dareka!",
     "救命！来人啊！", "Help! Someone!"),
    ("警察", "keisatsu", "警察", "Police", "emergency",
     "警察を呼んでください。", "keisatsu wo yonde kudasai.",
     "请叫警察。", "Please call the police."),
    ("病院", "byouin", "医院", "Hospital", "emergency",
     "近くの病院はどこですか？", "chikaku no byouin wa doko desu ka?",
     "附近的医院在哪里？", "Where's a nearby hospital?"),

    # feelings
    ("嬉しい", "ureshii", "高兴", "Happy", "feelings",
     "会えて嬉しいです。", "aete ureshii desu.",
     "见到你很高兴。", "I'm happy to see you."),
    ("疲れた", "tsukareta", "累", "Tired", "feelings",
     "今日はすごく疲れた。", "kyou wa sugoku tsukareta.",
     "今天特别累。", "I'm really tired today."),
    ("愛してる", "aishiteru", "我爱你", "I love you", "feelings",
     "ずっと愛してるよ。", "zutto aishiteru yo.",
     "我一直爱你。", "I'll always love you."),

    # phrases - idiomatic
    ("頑張って", "ganbatte", "加油", "Good luck / Go for it", "phrases",
     "明日の試験、頑張って！", "ashita no shiken, ganbatte!",
     "明天考试加油！", "Good luck on tomorrow's exam!"),
    ("お疲れ様です", "otsukaresama desu", "辛苦了（常用招呼）", "Thanks for your work", "phrases",
     "一日お疲れ様でした。", "ichinichi otsukaresama deshita.",
     "今天辛苦了。", "Thanks for a hard day's work."),
    ("よろしくお願いします", "yoroshiku onegaishimasu", "请多关照", "Please take care of me", "phrases",
     "初めまして、よろしくお願いします。", "hajimemashite, yoroshiku onegaishimasu.",
     "初次见面，请多关照。", "Nice to meet you, please take care of me."),
    ("いただきます", "itadakimasu", "我开动了（饭前）", "Let's eat (before meal)", "phrases",
     "いただきます！", "itadakimasu!",
     "开动了！", "Let's eat!"),
    ("ごちそうさま", "gochisousama", "谢谢款待（饭后）", "Thanks for the meal", "phrases",
     "ごちそうさまでした、とてもおいしかったです。", "gochisousama deshita, totemo oishikatta desu.",
     "谢谢款待，非常好吃。", "Thanks for the meal, it was delicious."),
    ("わかりません", "wakarimasen", "不明白", "I don't understand", "phrases",
     "すみません、意味がわかりません。", "sumimasen, imi ga wakarimasen.",
     "抱歉，我不明白意思。", "Sorry, I don't understand the meaning."),
    ("もう一度お願いします", "mou ichido onegaishimasu", "请再说一遍", "Once more please", "phrases",
     "すみません、もう一度お願いします。", "sumimasen, mou ichido onegaishimasu.",
     "抱歉，请再说一遍。", "Sorry, once more please."),
    ("お名前は？", "onamae wa?", "问姓名", "What's your name?", "phrases",
     "失礼ですが、お名前は？", "shitsurei desu ga, onamae wa?",
     "冒昧问一下，请问您叫什么？", "Excuse me, what's your name?"),
]
