# Korean 韩语 — curated core vocab with Revised Romanization + example sentences.
VOCAB = [
    ("안녕하세요", "annyeonghaseyo", "你好（敬语）", "Hello (polite)", "greetings",
     "안녕하세요, 처음 뵙겠습니다.", "annyeonghaseyo, cheoeum boepgetseumnida.",
     "你好，初次见面。", "Hello, nice to meet you for the first time."),
    ("감사합니다", "gamsahamnida", "谢谢（敬语）", "Thank you (polite)", "greetings",
     "도와주셔서 감사합니다.", "dowajusyeoseo gamsahamnida.",
     "谢谢你的帮助。", "Thank you for helping me."),
    ("죄송합니다", "joesonghamnida", "对不起", "Sorry", "greetings",
     "늦어서 죄송합니다.", "neujeoseo joesonghamnida.",
     "抱歉我来晚了。", "Sorry for being late."),
    ("괜찮아요", "gwaenchanayo", "没关系／没事", "It's okay", "greetings",
     "정말 괜찮아요, 걱정 마세요.", "jeongmal gwaenchanayo, geokjeong maseyo.",
     "真的没关系，别担心。", "It's really fine, don't worry."),
    ("안녕히 가세요", "annyeonghi gaseyo", "再见（对要离开的人）", "Goodbye (to the one leaving)", "greetings",
     "안녕히 가세요, 또 뵙겠습니다.", "annyeonghi gaseyo, tto boepgetseumnida.",
     "再见，下次再见。", "Goodbye, see you next time."),

    ("일", "il", "1", "One", "numbers",
     "일층에 있어요.", "il cheunge isseoyo.",
     "在一楼。", "It's on the first floor."),
    ("이", "i", "2", "Two", "numbers",
     "이 인분 주세요.", "i inbun juseyo.",
     "请给我两人份。", "Two servings, please."),
    ("삼", "sam", "3", "Three", "numbers",
     "삼월에 만나요.", "samwore mannayo.",
     "三月见。", "Let's meet in March."),
    ("십", "sip", "10", "Ten", "numbers",
     "십 분만 기다려 주세요.", "sip bunman gidaryeo juseyo.",
     "请等十分钟。", "Please wait ten minutes."),

    ("오늘", "oneul", "今天", "Today", "time",
     "오늘 날씨가 좋네요.", "oneul nalssiga jonneyo.",
     "今天天气真好。", "The weather is nice today."),
    ("내일", "naeil", "明天", "Tomorrow", "time",
     "내일 다시 올게요.", "naeil dasi olgeyo.",
     "明天再来。", "I'll come again tomorrow."),
    ("어제", "eoje", "昨天", "Yesterday", "time",
     "어제 친구를 만났어요.", "eoje chingureul mannasseoyo.",
     "昨天见了朋友。", "I met a friend yesterday."),
    ("지금", "jigeum", "现在", "Now", "time",
     "지금 어디예요?", "jigeum eodiyeyo?",
     "你现在在哪里？", "Where are you now?"),

    ("아빠", "appa", "爸爸", "Dad", "family",
     "아빠, 언제 집에 와요?", "appa, eonje jibe wayo?",
     "爸爸，什么时候回家？", "Dad, when are you coming home?"),
    ("엄마", "eomma", "妈妈", "Mom", "family",
     "엄마가 제일 좋아요.", "eommaga jeil joayo.",
     "最喜欢妈妈。", "I love mom the most."),
    ("친구", "chingu", "朋友", "Friend", "family",
     "제일 친한 친구예요.", "jeil chinhan chinguyeyo.",
     "是最好的朋友。", "He/She is my best friend."),

    ("밥", "bap", "米饭", "Rice / Meal", "food",
     "밥 먹었어요?", "bap meogeosseoyo?",
     "吃饭了吗？", "Have you eaten?"),
    ("김치", "gimchi", "泡菜", "Kimchi", "food",
     "김치 없이 밥을 못 먹어요.", "gimchi eopsi babeul mot meogeoyo.",
     "没有泡菜我吃不下饭。", "I can't eat without kimchi."),
    ("비빔밥", "bibimbap", "拌饭", "Bibimbap", "food",
     "비빔밥 한 그릇 주세요.", "bibimbap han geureut juseyo.",
     "请来一碗拌饭。", "One bibimbap, please."),
    ("차", "cha", "茶", "Tea", "food",
     "따뜻한 차 좀 주세요.", "ttatteutan cha jom juseyo.",
     "请给我一杯热茶。", "A hot tea, please."),
    ("물", "mul", "水", "Water", "food",
     "물 한 잔 주세요.", "mul han jan juseyo.",
     "请给我一杯水。", "A glass of water, please."),
    ("맛있어요", "masisseoyo", "好吃", "Delicious", "food",
     "이 음식이 진짜 맛있어요.", "i eumsigi jinjja masisseoyo.",
     "这道菜真好吃。", "This food is really delicious."),
    ("배고파요", "baegopayo", "饿", "I'm hungry", "food",
     "너무 배고파요, 밥 먹어요.", "neomu baegopayo, bap meogeoyo.",
     "太饿了，吃饭吧。", "I'm so hungry, let's eat."),

    ("어디예요", "eodiyeyo", "在哪里", "Where?", "travel",
     "화장실이 어디예요?", "hwajangsiri eodiyeyo?",
     "洗手间在哪里？", "Where's the restroom?"),
    ("공항", "gonghang", "机场", "Airport", "travel",
     "공항까지 얼마나 걸려요?", "gonghangkkaji eolmana geollyeoyo?",
     "到机场要多久？", "How long to the airport?"),
    ("호텔", "hotel", "酒店", "Hotel", "travel",
     "호텔은 역에서 가까워요.", "hotereun yeogeseo gakkawoyo.",
     "酒店离车站很近。", "The hotel is near the station."),
    ("왼쪽", "oenjjok", "左", "Left", "travel",
     "왼쪽으로 가세요.", "oenjjogeuro gaseyo.",
     "请往左走。", "Please go left."),
    ("오른쪽", "oreunjjok", "右", "Right", "travel",
     "오른쪽에 있어요.", "oreunjjoge isseoyo.",
     "在右边。", "It's on the right."),

    ("얼마예요", "eolmayeyo", "多少钱", "How much?", "shopping",
     "이거 얼마예요?", "igeo eolmayeyo?",
     "这个多少钱？", "How much is this?"),
    ("너무 비싸요", "neomu bissayo", "太贵", "Too expensive", "shopping",
     "너무 비싸요, 좀 깎아 주세요.", "neomu bissayo, jom kkakka juseyo.",
     "太贵了，便宜一点吧。", "Too expensive, can you discount?"),
    ("싸요", "ssayo", "便宜", "Cheap", "shopping",
     "이거 진짜 싸네요.", "igeo jinjja ssaneyo.",
     "这个真便宜。", "This is really cheap."),

    ("도와주세요", "dowajuseyo", "请帮忙", "Help me", "emergency",
     "죄송하지만 도와주세요.", "joesonghajiman dowajuseyo.",
     "不好意思，请帮帮我。", "Excuse me, please help me."),
    ("병원", "byeongwon", "医院", "Hospital", "emergency",
     "가장 가까운 병원이 어디예요?", "gajang gakkaun byeongwoni eodiyeyo?",
     "最近的医院在哪里？", "Where's the closest hospital?"),
    ("경찰", "gyeongchal", "警察", "Police", "emergency",
     "경찰을 불러 주세요.", "gyeongchareul bulleo juseyo.",
     "请叫警察。", "Please call the police."),

    ("행복해요", "haengbokhaeyo", "幸福", "Happy", "feelings",
     "당신이 있어서 행복해요.", "dangsini isseoseo haengbokhaeyo.",
     "因为有你我很幸福。", "I'm happy because you're here."),
    ("피곤해요", "pigonhaeyo", "累", "Tired", "feelings",
     "오늘 너무 피곤해요.", "oneul neomu pigonhaeyo.",
     "今天好累。", "I'm so tired today."),
    ("사랑해요", "saranghaeyo", "我爱你", "I love you", "feelings",
     "영원히 사랑해요.", "yeongwonhi saranghaeyo.",
     "永远爱你。", "I'll love you forever."),

    ("화이팅", "hwaiting", "加油", "Fighting / Go!", "phrases",
     "시험 잘 봐요, 화이팅!", "siheom jal bwayo, hwaiting!",
     "考试加油！", "Do well on the exam, fighting!"),
    ("수고하세요", "sugohaseyo", "辛苦了（常用）", "Good work / Take care", "phrases",
     "일 끝나고 수고하셨어요.", "il kkeutnago sugohasyeosseoyo.",
     "工作辛苦了。", "Good work finishing up."),
    ("대박", "daebak", "厉害／赞", "Awesome / No way!", "phrases",
     "와, 이거 진짜 대박이다!", "wa, igeo jinjja daebagida!",
     "哇，这太厉害了！", "Wow, this is awesome!"),
    ("잘 먹겠습니다", "jal meokgetseumnida", "我开动了（饭前）", "Thanks for the meal (before)", "phrases",
     "잘 먹겠습니다!", "jal meokgetseumnida!",
     "我开动了！", "Thanks for the meal!"),
    ("몰라요", "mollayo", "不知道／不懂", "I don't know", "phrases",
     "죄송하지만 몰라요.", "joesonghajiman mollayo.",
     "抱歉我不知道。", "Sorry, I don't know."),
    ("천천히 말해 주세요", "cheoncheonhi malhae juseyo", "请说慢点", "Please speak slowly", "phrases",
     "한국어 초보예요, 천천히 말해 주세요.", "hangugeo choboyeyo, cheoncheonhi malhae juseyo.",
     "我是韩语初学者，请说慢点。", "I'm a Korean beginner, please speak slowly."),
    ("이름이 뭐예요?", "ireumi mwoyeyo?", "问姓名", "What's your name?", "phrases",
     "안녕하세요, 이름이 뭐예요?", "annyeonghaseyo, ireumi mwoyeyo?",
     "你好，你叫什么名字？", "Hello, what's your name?"),
]
