# Mandarin 普通话 — curated core vocab with Pinyin + example sentences.
VOCAB = [
    # ============ greetings ============
    ("你好", "nǐ hǎo", "问候", "Hello", "greetings",
     "你好！很高兴认识你。", "nǐ hǎo! hěn gāo xìng rèn shi nǐ.",
     "你好！很高兴认识你。", "Hello! Nice to meet you."),
    ("你好吗", "nǐ hǎo ma", "问近况", "How are you?", "greetings",
     "最近你好吗？", "zuì jìn nǐ hǎo ma?",
     "最近你好吗？", "How have you been recently?"),
    ("早上好", "zǎo shàng hǎo", "早晨问候", "Good morning", "greetings",
     "早上好，今天天气真不错！", "zǎo shàng hǎo, jīn tiān tiān qì zhēn bú cuò!",
     "早上好，今天天气真不错！", "Good morning, what lovely weather today!"),
    ("晚上好", "wǎn shàng hǎo", "晚间问候", "Good evening", "greetings",
     "晚上好，欢迎光临。", "wǎn shàng hǎo, huān yíng guāng lín.",
     "晚上好，欢迎光临。", "Good evening, welcome!"),
    ("谢谢", "xiè xie", "感谢", "Thank you", "greetings",
     "谢谢你的帮助。", "xiè xie nǐ de bāng zhù.",
     "谢谢你的帮助。", "Thank you for your help."),
    ("不客气", "bú kè qi", "回应感谢", "You're welcome", "greetings",
     "不客气，这是我应该做的。", "bú kè qi, zhè shì wǒ yīng gāi zuò de.",
     "不客气，这是我应该做的。", "You're welcome, it's the least I could do."),
    ("对不起", "duì bu qǐ", "道歉", "Sorry", "greetings",
     "对不起，我迟到了。", "duì bu qǐ, wǒ chí dào le.",
     "对不起，我迟到了。", "Sorry, I'm late."),
    ("没关系", "méi guān xi", "宽容回应", "It's okay", "greetings",
     "没关系，下次注意就好。", "méi guān xi, xià cì zhù yì jiù hǎo.",
     "没关系，下次注意就好。", "It's okay, just be careful next time."),
    ("再见", "zài jiàn", "告别", "Goodbye", "greetings",
     "再见，周末愉快！", "zài jiàn, zhōu mò yú kuài!",
     "再见，周末愉快！", "Goodbye, have a great weekend!"),
    ("晚安", "wǎn ān", "睡前道别", "Good night", "greetings",
     "晚安，做个好梦。", "wǎn ān, zuò gè hǎo mèng.",
     "晚安，做个好梦。", "Good night, sweet dreams."),

    # ============ numbers ============
    ("一", "yī", "1", "One", "numbers",
     "我只要一个。", "wǒ zhǐ yào yī ge.",
     "我只要一个。", "I just want one."),
    ("二", "èr", "2", "Two", "numbers",
     "请给我两杯咖啡。", "qǐng gěi wǒ liǎng bēi kā fēi.",
     "请给我两杯咖啡。", "Please give me two cups of coffee."),
    ("三", "sān", "3", "Three", "numbers",
     "我有三个兄弟姐妹。", "wǒ yǒu sān gè xiōng dì jiě mèi.",
     "我有三个兄弟姐妹。", "I have three siblings."),
    ("四", "sì", "4", "Four", "numbers",
     "一年有四个季节。", "yì nián yǒu sì ge jì jié.",
     "一年有四个季节。", "There are four seasons in a year."),
    ("五", "wǔ", "5", "Five", "numbers",
     "我五点下班。", "wǒ wǔ diǎn xià bān.",
     "我五点下班。", "I get off work at five."),
    ("六", "liù", "6", "Six", "numbers",
     "这盒有六块巧克力。", "zhè hé yǒu liù kuài qiǎo kè lì.",
     "这盒有六块巧克力。", "There are six pieces of chocolate in this box."),
    ("七", "qī", "7", "Seven", "numbers",
     "一周有七天。", "yì zhōu yǒu qī tiān.",
     "一周有七天。", "A week has seven days."),
    ("八", "bā", "8", "Eight", "numbers",
     "八是我的幸运数字。", "bā shì wǒ de xìng yùn shù zì.",
     "八是我的幸运数字。", "Eight is my lucky number."),
    ("九", "jiǔ", "9", "Nine", "numbers",
     "商店九点开门。", "shāng diàn jiǔ diǎn kāi mén.",
     "商店九点开门。", "The shop opens at nine."),
    ("十", "shí", "10", "Ten", "numbers",
     "我们十分钟后见。", "wǒ men shí fēn zhōng hòu jiàn.",
     "我们十分钟后见。", "Let's meet in ten minutes."),
    ("一百", "yì bǎi", "100", "One hundred", "numbers",
     "这件衣服一百块。", "zhè jiàn yī fu yì bǎi kuài.",
     "这件衣服一百块。", "This piece of clothing costs 100 yuan."),
    ("一千", "yì qiān", "1000", "One thousand", "numbers",
     "我存了一千块钱。", "wǒ cún le yì qiān kuài qián.",
     "我存了一千块钱。", "I saved a thousand yuan."),

    # ============ time ============
    ("今天", "jīn tiān", "今日", "Today", "time",
     "今天是星期三。", "jīn tiān shì xīng qī sān.",
     "今天是星期三。", "Today is Wednesday."),
    ("明天", "míng tiān", "次日", "Tomorrow", "time",
     "明天见！", "míng tiān jiàn!",
     "明天见！", "See you tomorrow!"),
    ("昨天", "zuó tiān", "前一日", "Yesterday", "time",
     "我昨天去看了电影。", "wǒ zuó tiān qù kàn le diàn yǐng.",
     "我昨天去看了电影。", "I went to see a movie yesterday."),
    ("现在", "xiàn zài", "此刻", "Now", "time",
     "现在几点了？", "xiàn zài jǐ diǎn le?",
     "现在几点了？", "What time is it now?"),
    ("早上", "zǎo shang", "清晨", "Morning", "time",
     "我每天早上跑步。", "wǒ měi tiān zǎo shang pǎo bù.",
     "我每天早上跑步。", "I go running every morning."),
    ("中午", "zhōng wǔ", "中午", "Noon", "time",
     "中午我们一起吃饭吧。", "zhōng wǔ wǒ men yì qǐ chī fàn ba.",
     "中午我们一起吃饭吧。", "Let's eat lunch together at noon."),
    ("晚上", "wǎn shang", "夜晚", "Evening", "time",
     "晚上我通常看书。", "wǎn shang wǒ tōng cháng kàn shū.",
     "晚上我通常看书。", "I usually read in the evening."),
    ("几点了", "jǐ diǎn le", "询问时间", "What time is it?", "time",
     "请问几点了？", "qǐng wèn jǐ diǎn le?",
     "请问几点了？", "Excuse me, what time is it?"),
    ("等一下", "děng yí xià", "请求稍等", "Wait a moment", "time",
     "等一下，我马上来。", "děng yí xià, wǒ mǎ shàng lái.",
     "等一下，我马上来。", "Wait a moment, I'm coming right away."),
    ("星期", "xīng qī", "一周", "Week", "time",
     "下个星期我要出差。", "xià ge xīng qī wǒ yào chū chāi.",
     "下个星期我要出差。", "I'm going on a business trip next week."),

    # ============ family ============
    ("爸爸", "bà ba", "父亲", "Dad", "family",
     "我爸爸是医生。", "wǒ bà ba shì yī shēng.",
     "我爸爸是医生。", "My dad is a doctor."),
    ("妈妈", "mā ma", "母亲", "Mom", "family",
     "妈妈做的菜最好吃。", "mā ma zuò de cài zuì hǎo chī.",
     "妈妈做的菜最好吃。", "Mom's cooking is the best."),
    ("哥哥", "gē ge", "兄长", "Older brother", "family",
     "我哥哥比我大三岁。", "wǒ gē ge bǐ wǒ dà sān suì.",
     "我哥哥比我大三岁。", "My older brother is three years older than me."),
    ("姐姐", "jiě jie", "姐姐", "Older sister", "family",
     "姐姐在大学读书。", "jiě jie zài dà xué dú shū.",
     "姐姐在大学读书。", "My older sister studies at university."),
    ("弟弟", "dì di", "弟弟", "Younger brother", "family",
     "我弟弟还在上小学。", "wǒ dì di hái zài shàng xiǎo xué.",
     "我弟弟还在上小学。", "My younger brother is still in primary school."),
    ("妹妹", "mèi mei", "妹妹", "Younger sister", "family",
     "妹妹喜欢画画。", "mèi mei xǐ huan huà huà.",
     "妹妹喜欢画画。", "My younger sister likes to draw."),
    ("朋友", "péng you", "友人", "Friend", "family",
     "他是我最好的朋友。", "tā shì wǒ zuì hǎo de péng you.",
     "他是我最好的朋友。", "He is my best friend."),
    ("孩子", "hái zi", "儿童", "Child", "family",
     "孩子们在公园里玩。", "hái zi men zài gōng yuán lǐ wán.",
     "孩子们在公园里玩。", "The children are playing in the park."),

    # ============ food ============
    ("米饭", "mǐ fàn", "主食", "Rice", "food",
     "我要一碗米饭。", "wǒ yào yì wǎn mǐ fàn.",
     "我要一碗米饭。", "I'd like a bowl of rice."),
    ("面条", "miàn tiáo", "面食", "Noodles", "food",
     "这家店的面条很好吃。", "zhè jiā diàn de miàn tiáo hěn hǎo chī.",
     "这家店的面条很好吃。", "The noodles at this restaurant are delicious."),
    ("饺子", "jiǎo zi", "传统面食", "Dumplings", "food",
     "过年我们全家一起包饺子。", "guò nián wǒ men quán jiā yì qǐ bāo jiǎo zi.",
     "过年我们全家一起包饺子。", "At Chinese New Year, our whole family makes dumplings together."),
    ("包子", "bāo zi", "蒸面食", "Steamed bun", "food",
     "早餐我吃了两个包子。", "zǎo cān wǒ chī le liǎng gè bāo zi.",
     "早餐我吃了两个包子。", "I had two steamed buns for breakfast."),
    ("茶", "chá", "传统饮品", "Tea", "food",
     "中国人喜欢喝茶。", "zhōng guó rén xǐ huan hē chá.",
     "中国人喜欢喝茶。", "Chinese people like to drink tea."),
    ("水", "shuǐ", "饮用水", "Water", "food",
     "请给我一杯水。", "qǐng gěi wǒ yì bēi shuǐ.",
     "请给我一杯水。", "Please give me a glass of water."),
    ("咖啡", "kā fēi", "咖啡", "Coffee", "food",
     "我每天早上喝一杯咖啡。", "wǒ měi tiān zǎo shang hē yì bēi kā fēi.",
     "我每天早上喝一杯咖啡。", "I drink a cup of coffee every morning."),
    ("啤酒", "pí jiǔ", "酒类", "Beer", "food",
     "他喝了两瓶啤酒。", "tā hē le liǎng píng pí jiǔ.",
     "他喝了两瓶啤酒。", "He drank two bottles of beer."),
    ("水果", "shuǐ guǒ", "水果", "Fruit", "food",
     "多吃水果对身体好。", "duō chī shuǐ guǒ duì shēn tǐ hǎo.",
     "多吃水果对身体好。", "Eating more fruit is good for your health."),
    ("苹果", "píng guǒ", "苹果", "Apple", "food",
     "一天一个苹果，医生远离我。", "yì tiān yí ge píng guǒ, yī shēng yuǎn lí wǒ.",
     "一天一个苹果，医生远离我。", "An apple a day keeps the doctor away."),
    ("好吃", "hǎo chī", "美味", "Tasty", "food",
     "这个蛋糕真好吃！", "zhè ge dàn gāo zhēn hǎo chī!",
     "这个蛋糕真好吃！", "This cake is really tasty!"),
    ("辣", "là", "辛辣", "Spicy", "food",
     "四川菜很辣。", "sì chuān cài hěn là.",
     "四川菜很辣。", "Sichuan food is very spicy."),
    ("我饿了", "wǒ è le", "表达饥饿", "I'm hungry", "food",
     "我饿了，我们吃饭吧。", "wǒ è le, wǒ men chī fàn ba.",
     "我饿了，我们吃饭吧。", "I'm hungry, let's eat."),
    ("菜单", "cài dān", "菜谱", "Menu", "food",
     "请给我菜单。", "qǐng gěi wǒ cài dān.",
     "请给我菜单。", "Please give me the menu."),

    # ============ colors ============
    ("红色", "hóng sè", "红色", "Red", "colors",
     "我喜欢红色的花。", "wǒ xǐ huan hóng sè de huā.",
     "我喜欢红色的花。", "I like red flowers."),
    ("蓝色", "lán sè", "蓝色", "Blue", "colors",
     "天空是蓝色的。", "tiān kōng shì lán sè de.",
     "天空是蓝色的。", "The sky is blue."),
    ("黄色", "huáng sè", "黄色", "Yellow", "colors",
     "这件黄色的衣服很漂亮。", "zhè jiàn huáng sè de yī fu hěn piào liang.",
     "这件黄色的衣服很漂亮。", "This yellow dress is very pretty."),
    ("绿色", "lǜ sè", "绿色", "Green", "colors",
     "春天树叶变绿了。", "chūn tiān shù yè biàn lǜ le.",
     "春天树叶变绿了。", "The leaves turn green in spring."),
    ("白色", "bái sè", "白色", "White", "colors",
     "雪是白色的。", "xuě shì bái sè de.",
     "雪是白色的。", "Snow is white."),
    ("黑色", "hēi sè", "黑色", "Black", "colors",
     "他穿了一件黑色的外套。", "tā chuān le yí jiàn hēi sè de wài tào.",
     "他穿了一件黑色的外套。", "He's wearing a black coat."),

    # ============ body ============
    ("头", "tóu", "头部", "Head", "body",
     "我头疼。", "wǒ tóu téng.",
     "我头疼。", "I have a headache."),
    ("眼睛", "yǎn jing", "眼睛", "Eye", "body",
     "她的眼睛又大又亮。", "tā de yǎn jing yòu dà yòu liàng.",
     "她的眼睛又大又亮。", "Her eyes are big and bright."),
    ("手", "shǒu", "手", "Hand", "body",
     "吃饭前要洗手。", "chī fàn qián yào xǐ shǒu.",
     "吃饭前要洗手。", "Wash your hands before eating."),
    ("脚", "jiǎo", "脚", "Foot", "body",
     "走了一天，脚很酸。", "zǒu le yì tiān, jiǎo hěn suān.",
     "走了一天，脚很酸。", "After walking all day, my feet ache."),
    ("心", "xīn", "心脏／心", "Heart", "body",
     "我的心跳得很快。", "wǒ de xīn tiào de hěn kuài.",
     "我的心跳得很快。", "My heart is beating fast."),

    # ============ weather ============
    ("天气", "tiān qì", "气象", "Weather", "weather",
     "今天天气怎么样？", "jīn tiān tiān qì zěn me yàng?",
     "今天天气怎么样？", "How's the weather today?"),
    ("下雨", "xià yǔ", "降雨", "Rain", "weather",
     "外面在下雨，别忘了带伞。", "wài miàn zài xià yǔ, bié wàng le dài sǎn.",
     "外面在下雨，别忘了带伞。", "It's raining outside, don't forget your umbrella."),
    ("下雪", "xià xuě", "降雪", "Snow", "weather",
     "北京冬天经常下雪。", "běi jīng dōng tiān jīng cháng xià xuě.",
     "北京冬天经常下雪。", "It often snows in Beijing in winter."),
    ("晴天", "qíng tiān", "晴朗", "Sunny day", "weather",
     "今天是个大晴天。", "jīn tiān shì ge dà qíng tiān.",
     "今天是个大晴天。", "Today is a beautiful sunny day."),
    ("风", "fēng", "风", "Wind", "weather",
     "今天风很大。", "jīn tiān fēng hěn dà.",
     "今天风很大。", "It's very windy today."),

    # ============ travel ============
    ("在哪里", "zài nǎ lǐ", "询问位置", "Where is it?", "travel",
     "请问地铁站在哪里？", "qǐng wèn dì tiě zhàn zài nǎ lǐ?",
     "请问地铁站在哪里？", "Excuse me, where is the subway station?"),
    ("怎么去", "zěn me qù", "询问路线", "How to get there?", "travel",
     "请问机场怎么去？", "qǐng wèn jī chǎng zěn me qù?",
     "请问机场怎么去？", "Excuse me, how do I get to the airport?"),
    ("机场", "jī chǎng", "飞机场", "Airport", "travel",
     "我要去机场。", "wǒ yào qù jī chǎng.",
     "我要去机场。", "I need to go to the airport."),
    ("火车站", "huǒ chē zhàn", "火车站", "Train station", "travel",
     "火车站离这里远吗？", "huǒ chē zhàn lí zhè lǐ yuǎn ma?",
     "火车站离这里远吗？", "Is the train station far from here?"),
    ("酒店", "jiǔ diàn", "住宿", "Hotel", "travel",
     "我们住在这家酒店。", "wǒ men zhù zài zhè jiā jiǔ diàn.",
     "我们住在这家酒店。", "We're staying at this hotel."),
    ("票", "piào", "车票／门票", "Ticket", "travel",
     "我买了两张票。", "wǒ mǎi le liǎng zhāng piào.",
     "我买了两张票。", "I bought two tickets."),
    ("左", "zuǒ", "左边", "Left", "travel",
     "向左转就到了。", "xiàng zuǒ zhuǎn jiù dào le.",
     "向左转就到了。", "Turn left and you're there."),
    ("右", "yòu", "右边", "Right", "travel",
     "洗手间在右边。", "xǐ shǒu jiān zài yòu bian.",
     "洗手间在右边。", "The restroom is on the right."),
    ("直走", "zhí zǒu", "向前走", "Go straight", "travel",
     "一直走到红绿灯。", "yì zhí zǒu dào hóng lǜ dēng.",
     "一直走到红绿灯。", "Go straight until the traffic light."),
    ("停", "tíng", "停止", "Stop", "travel",
     "司机，在这里停一下。", "sī jī, zài zhè lǐ tíng yí xià.",
     "司机，在这里停一下。", "Driver, please stop here."),

    # ============ shopping ============
    ("多少钱", "duō shǎo qián", "询问价格", "How much?", "shopping",
     "这个多少钱？", "zhè ge duō shǎo qián?",
     "这个多少钱？", "How much is this?"),
    ("太贵了", "tài guì le", "价格高", "Too expensive", "shopping",
     "太贵了，能便宜一点吗？", "tài guì le, néng pián yi yì diǎn ma?",
     "太贵了，能便宜一点吗？", "Too expensive, can you make it cheaper?"),
    ("便宜", "pián yi", "价格低", "Cheap", "shopping",
     "这家店东西很便宜。", "zhè jiā diàn dōng xi hěn pián yi.",
     "这家店东西很便宜。", "Things at this shop are cheap."),
    ("这个", "zhè ge", "指示", "This one", "shopping",
     "我要这个，谢谢。", "wǒ yào zhè ge, xiè xie.",
     "我要这个，谢谢。", "I'll take this one, thanks."),
    ("刷卡", "shuā kǎ", "用卡付款", "Pay by card", "shopping",
     "可以刷卡吗？", "kě yǐ shuā kǎ ma?",
     "可以刷卡吗？", "Can I pay by card?"),
    ("收据", "shōu jù", "购物凭证", "Receipt", "shopping",
     "请给我收据。", "qǐng gěi wǒ shōu jù.",
     "请给我收据。", "Please give me a receipt."),

    # ============ emergency ============
    ("救命", "jiù mìng", "呼救", "Help!", "emergency",
     "救命啊！有小偷！", "jiù mìng a! yǒu xiǎo tōu!",
     "救命啊！有小偷！", "Help! There's a thief!"),
    ("警察", "jǐng chá", "治安人员", "Police", "emergency",
     "请叫警察。", "qǐng jiào jǐng chá.",
     "请叫警察。", "Please call the police."),
    ("医生", "yī shēng", "医务人员", "Doctor", "emergency",
     "我需要看医生。", "wǒ xū yào kàn yī shēng.",
     "我需要看医生。", "I need to see a doctor."),
    ("医院", "yī yuàn", "医疗场所", "Hospital", "emergency",
     "最近的医院在哪里？", "zuì jìn de yī yuàn zài nǎ lǐ?",
     "最近的医院在哪里？", "Where is the nearest hospital?"),
    ("我迷路了", "wǒ mí lù le", "找不到路", "I'm lost", "emergency",
     "我迷路了，能帮帮我吗？", "wǒ mí lù le, néng bāng bang wǒ ma?",
     "我迷路了，能帮帮我吗？", "I'm lost, can you help me?"),
    ("报警", "bào jǐng", "呼叫警察", "Call police", "emergency",
     "快报警！", "kuài bào jǐng!",
     "快报警！", "Call the police quickly!"),

    # ============ feelings ============
    ("开心", "kāi xīn", "高兴", "Happy", "feelings",
     "收到礼物我很开心。", "shōu dào lǐ wù wǒ hěn kāi xīn.",
     "收到礼物我很开心。", "I'm very happy to receive a gift."),
    ("难过", "nán guò", "伤心", "Sad", "feelings",
     "听到这个消息我很难过。", "tīng dào zhè ge xiāo xi wǒ hěn nán guò.",
     "听到这个消息我很难过。", "I'm sad to hear this news."),
    ("生气", "shēng qì", "愤怒", "Angry", "feelings",
     "他为什么这么生气？", "tā wèi shén me zhè me shēng qì?",
     "他为什么这么生气？", "Why is he so angry?"),
    ("累", "lèi", "疲倦", "Tired", "feelings",
     "今天工作很忙，我很累。", "jīn tiān gōng zuò hěn máng, wǒ hěn lèi.",
     "今天工作很忙，我很累。", "Work was busy today, I'm really tired."),
    ("害怕", "hài pà", "恐惧", "Afraid", "feelings",
     "我害怕黑。", "wǒ hài pà hēi.",
     "我害怕黑。", "I'm afraid of the dark."),
    ("爱", "ài", "深挚感情", "Love", "feelings",
     "我爱我的家人。", "wǒ ài wǒ de jiā rén.",
     "我爱我的家人。", "I love my family."),
    ("想你", "xiǎng nǐ", "思念", "Miss you", "feelings",
     "我很想你。", "wǒ hěn xiǎng nǐ.",
     "我很想你。", "I miss you very much."),

    # ============ verbs ============
    ("吃", "chī", "进食", "Eat", "verbs",
     "你吃过午饭了吗？", "nǐ chī guo wǔ fàn le ma?",
     "你吃过午饭了吗？", "Have you had lunch yet?"),
    ("喝", "hē", "饮用", "Drink", "verbs",
     "我要喝点热的。", "wǒ yào hē diǎn rè de.",
     "我要喝点热的。", "I'd like to drink something hot."),
    ("去", "qù", "前往", "Go", "verbs",
     "你去哪里？", "nǐ qù nǎ lǐ?",
     "你去哪里？", "Where are you going?"),
    ("来", "lái", "到来", "Come", "verbs",
     "他明天来我家。", "tā míng tiān lái wǒ jiā.",
     "他明天来我家。", "He's coming to my house tomorrow."),
    ("看", "kàn", "观看", "See / Watch", "verbs",
     "我喜欢看电影。", "wǒ xǐ huan kàn diàn yǐng.",
     "我喜欢看电影。", "I like watching movies."),
    ("听", "tīng", "听闻", "Listen", "verbs",
     "我每天听音乐。", "wǒ měi tiān tīng yīn yuè.",
     "我每天听音乐。", "I listen to music every day."),
    ("说", "shuō", "说话", "Speak", "verbs",
     "请说慢一点。", "qǐng shuō màn yì diǎn.",
     "请说慢一点。", "Please speak slower."),
    ("买", "mǎi", "购买", "Buy", "verbs",
     "我想买一件毛衣。", "wǒ xiǎng mǎi yí jiàn máo yī.",
     "我想买一件毛衣。", "I want to buy a sweater."),
    ("学习", "xué xí", "学习", "Study / Learn", "verbs",
     "我在学习中文。", "wǒ zài xué xí zhōng wén.",
     "我在学习中文。", "I'm learning Chinese."),
    ("工作", "gōng zuò", "工作", "Work", "verbs",
     "他在一家大公司工作。", "tā zài yì jiā dà gōng sī gōng zuò.",
     "他在一家大公司工作。", "He works at a big company."),

    # ============ adjectives ============
    ("大", "dà", "大", "Big", "adjectives",
     "这个房间很大。", "zhè ge fáng jiān hěn dà.",
     "这个房间很大。", "This room is very big."),
    ("小", "xiǎo", "小", "Small", "adjectives",
     "他的狗很小。", "tā de gǒu hěn xiǎo.",
     "他的狗很小。", "His dog is very small."),
    ("好", "hǎo", "好", "Good", "adjectives",
     "你是一个好人。", "nǐ shì yí ge hǎo rén.",
     "你是一个好人。", "You are a good person."),
    ("坏", "huài", "坏", "Bad", "adjectives",
     "这个牛奶坏了。", "zhè ge niú nǎi huài le.",
     "这个牛奶坏了。", "This milk has gone bad."),
    ("新", "xīn", "新", "New", "adjectives",
     "我买了一辆新车。", "wǒ mǎi le yí liàng xīn chē.",
     "我买了一辆新车。", "I bought a new car."),
    ("快", "kuài", "快速", "Fast", "adjectives",
     "高铁很快。", "gāo tiě hěn kuài.",
     "高铁很快。", "The high-speed train is very fast."),
    ("慢", "màn", "慢", "Slow", "adjectives",
     "请开慢一点。", "qǐng kāi màn yì diǎn.",
     "请开慢一点。", "Please drive slower."),

    # ============ phrases ============
    ("加油", "jiā yóu", "鼓励", "Go for it!", "phrases",
     "明天考试，加油！", "míng tiān kǎo shì, jiā yóu!",
     "明天考试，加油！", "You have an exam tomorrow, good luck!"),
    ("不好意思", "bù hǎo yì si", "委婉道歉", "Excuse me / Sorry", "phrases",
     "不好意思，麻烦让一下。", "bù hǎo yì si, má fan ràng yí xià.",
     "不好意思，麻烦让一下。", "Excuse me, could you make way please."),
    ("随便", "suí biàn", "都可以", "Whatever / It's up to you", "phrases",
     "吃什么？随便，你决定。", "chī shén me? suí biàn, nǐ jué dìng.",
     "吃什么？随便，你决定。", "What should we eat? Up to you, you decide."),
    ("听不懂", "tīng bu dǒng", "没听明白", "I don't understand", "phrases",
     "对不起，我听不懂，你能再说一遍吗？", "duì bu qǐ, wǒ tīng bu dǒng, nǐ néng zài shuō yí biàn ma?",
     "对不起，我听不懂，你能再说一遍吗？", "Sorry, I didn't catch that, could you say it again?"),
    ("再见", "zài jiàn", "道别", "Goodbye", "phrases",
     "好，那再见！", "hǎo, nà zài jiàn!",
     "好，那再见！", "OK, then goodbye!"),
    ("谢谢你", "xiè xie nǐ", "致谢", "Thank you", "phrases",
     "谢谢你一直以来的支持。", "xiè xie nǐ yì zhí yǐ lái de zhī chí.",
     "谢谢你一直以来的支持。", "Thank you for your continuous support."),
    ("你叫什么名字", "nǐ jiào shén me míng zi", "问姓名", "What's your name?", "phrases",
     "请问你叫什么名字？", "qǐng wèn nǐ jiào shén me míng zi?",
     "请问你叫什么名字？", "May I ask your name?"),
    ("我叫……", "wǒ jiào...", "自我介绍", "My name is...", "phrases",
     "你好，我叫小明。", "nǐ hǎo, wǒ jiào xiǎo míng.",
     "你好，我叫小明。", "Hello, my name is Xiaoming."),
    ("很高兴认识你", "hěn gāo xìng rèn shi nǐ", "客套", "Nice to meet you", "phrases",
     "很高兴认识你，希望以后多联系。", "hěn gāo xìng rèn shi nǐ, xī wàng yǐ hòu duō lián xì.",
     "很高兴认识你，希望以后多联系。", "Nice to meet you, I hope we stay in touch."),
    ("慢点说", "màn diǎn shuō", "请求慢说", "Speak slower", "phrases",
     "能不能慢点说？", "néng bu néng màn diǎn shuō?",
     "能不能慢点说？", "Could you speak a bit slower?"),
]
