# Hokkien 闽南语 — curated core vocab with POJ + example sentences.
VOCAB = [
    ("汝好", "lí hó", "你好", "Hello", "greetings",
     "汝好，真久無看著汝。", "lí hó, chin-kú bô khòaⁿ-tio̍h lí.",
     "你好，很久没见你了。", "Hello, haven't seen you for a long time."),
    ("多謝", "to-siā", "谢谢（正式）", "Thank you (formal)", "greetings",
     "多謝汝的幫助。", "to-siā lí ê pang-chō͘.",
     "谢谢你的帮助。", "Thank you for your help."),
    ("失禮", "sit-lé", "对不起（正式）", "Sorry (formal)", "greetings",
     "失禮，我來慢矣。", "sit-lé, guá lâi bān ah.",
     "对不起，我来晚了。", "Sorry, I came late."),
    ("歹勢", "pháiⁿ-sè", "不好意思", "Excuse me (mild)", "greetings",
     "歹勢，借過一下。", "pháiⁿ-sè, chioh-kè chi̍t-ē.",
     "不好意思，借过一下。", "Excuse me, let me pass."),
    ("無要緊", "bô iàu-kín", "没关系", "It's okay / No worries", "greetings",
     "無要緊啦，免掛意。", "bô iàu-kín lah, bián kòa-ì.",
     "没关系，别挂心。", "It's okay, don't worry about it."),
    ("再會", "tsài-huē", "再见", "Goodbye", "greetings",
     "好，那再會！", "hó, nā tsài-huē!",
     "好，那再见！", "Okay, goodbye then!"),

    ("一", "chi̍t", "1", "One", "numbers",
     "我欲一碗飯。", "guá beh chi̍t óaⁿ pn̄g.",
     "我要一碗饭。", "I want one bowl of rice."),
    ("二", "nn̄g", "2", "Two", "numbers",
     "兩杯茶，多謝。", "nn̄g poe tê, to-siā.",
     "两杯茶，谢谢。", "Two cups of tea, thanks."),
    ("三", "saⁿ", "3", "Three", "numbers",
     "三點見面。", "saⁿ tiám kìⁿ-bīn.",
     "三点见面。", "Meet at three."),
    ("十", "cha̍p", "10", "Ten", "numbers",
     "等十分鐘。", "tán cha̍p hun-cheng.",
     "等十分钟。", "Wait ten minutes."),

    ("今仔日", "kin-á-ji̍t", "今天", "Today", "time",
     "今仔日天氣真好。", "kin-á-ji̍t thiⁿ-khì chin hó.",
     "今天天气真好。", "The weather is nice today."),
    ("明仔載", "bîn-á-tsài", "明天", "Tomorrow", "time",
     "明仔載閣來。", "bîn-á-tsài koh lâi.",
     "明天再来。", "Come again tomorrow."),
    ("昨昏", "tsa-hng", "昨天", "Yesterday", "time",
     "昨昏我去菜市。", "tsa-hng guá khì chhài-chhī.",
     "昨天我去菜市场。", "I went to the market yesterday."),
    ("這馬", "chit-má", "现在", "Now", "time",
     "這馬幾點？", "chit-má kúi tiám?",
     "现在几点？", "What time is it now?"),

    ("阿爸", "a-pa", "爸爸", "Dad", "family",
     "阿爸去田裡。", "a-pa khì chhân-ni̍h.",
     "爸爸去田里了。", "Dad went to the field."),
    ("阿母", "a-bú", "妈妈", "Mom", "family",
     "阿母煮飯真好食。", "a-bú chú-pn̄g chin hó-chia̍h.",
     "妈妈做的饭真好吃。", "Mom's cooking is delicious."),
    ("朋友", "pêng-iú", "朋友", "Friend", "family",
     "伊是我的好朋友。", "i sī guá ê hó pêng-iú.",
     "他/她是我的好朋友。", "He/She is my good friend."),

    ("飯", "pn̄g", "米饭", "Rice", "food",
     "飯食飽未？", "pn̄g chia̍h-pá--buē?",
     "吃饱饭了吗？", "Have you had your fill?"),
    ("麵", "mī", "面", "Noodles", "food",
     "這碗麵真好食。", "chit óaⁿ mī chin hó-chia̍h.",
     "这碗面真好吃。", "This bowl of noodles is tasty."),
    ("滷肉飯", "ló͘-bah-pn̄g", "卤肉饭", "Braised pork rice", "food",
     "滷肉飯是台灣的驕傲。", "ló͘-bah-pn̄g sī Tâi-oân ê kiau-ngō͘.",
     "卤肉饭是台湾的骄傲。", "Braised pork rice is Taiwan's pride."),
    ("茶", "tê", "茶", "Tea", "food",
     "食茶無？", "chia̍h tê bô?",
     "要喝茶吗？", "Want some tea?"),
    ("水", "tsuí", "水", "Water", "food",
     "請予我一杯水。", "chhiáⁿ hō͘ guá chi̍t poe tsuí.",
     "请给我一杯水。", "Please give me a cup of water."),
    ("好食", "hó-chia̍h", "好吃", "Tasty", "food",
     "真好食！", "chin hó-chia̍h!",
     "真好吃！", "Really delicious!"),

    ("佗位", "tó-uī", "哪里", "Where", "travel",
     "便所佇佗位？", "piān-só͘ tī tó-uī?",
     "厕所在哪里？", "Where's the restroom?"),
    ("機場", "ki-tiûⁿ", "机场", "Airport", "travel",
     "去機場按怎行？", "khì ki-tiûⁿ án-tsuáⁿ kiâⁿ?",
     "去机场怎么走？", "How to get to the airport?"),
    ("旅館", "lú-kuán", "旅馆／酒店", "Hotel", "travel",
     "我蹛這家旅館。", "guá tòa chit-ke lú-kuán.",
     "我住这家旅馆。", "I'm staying at this hotel."),
    ("倒爿", "tò-pêng", "左边", "Left", "travel",
     "倒爿彼間店。", "tò-pêng hit king tiàm.",
     "左边那家店。", "The shop on the left."),
    ("正爿", "chiàⁿ-pêng", "右边", "Right", "travel",
     "正爿有一个公園。", "chiàⁿ-pêng ū chi̍t ê kong-hn̂g.",
     "右边有个公园。", "There's a park on the right."),

    ("偌濟錢", "jōa-tsē tsîⁿ", "多少钱", "How much?", "shopping",
     "這个偌濟錢？", "chit-ê jōa-tsē tsîⁿ?",
     "这个多少钱？", "How much is this?"),
    ("傷貴", "siuⁿ kuì", "太贵", "Too expensive", "shopping",
     "傷貴矣，算俗咧。", "siuⁿ kuì ah, sǹg sio̍k--leh.",
     "太贵了，便宜点。", "Too expensive, give a discount."),
    ("俗", "sio̍k", "便宜", "Cheap", "shopping",
     "這真俗。", "che chin sio̍k.",
     "这真便宜。", "This is really cheap."),

    ("救人", "kiù-lâng", "救命", "Help!", "emergency",
     "救人喔！緊來！", "kiù-lâng ò͘! kín lâi!",
     "救命啊！快来！", "Help! Come quick!"),
    ("警察", "kéng-tshat", "警察", "Police", "emergency",
     "叫警察！", "kiò kéng-tshat!",
     "叫警察！", "Call the police!"),
    ("病院", "pēⁿ-īⁿ", "医院", "Hospital", "emergency",
     "上近的病院佇佗位？", "siōng kīn ê pēⁿ-īⁿ tī tó-uī?",
     "最近的医院在哪？", "Where's the nearest hospital?"),

    ("歡喜", "huaⁿ-hí", "高兴", "Happy", "feelings",
     "看著汝真歡喜。", "khòaⁿ-tio̍h lí chin huaⁿ-hí.",
     "见到你真高兴。", "I'm happy to see you."),
    ("忝", "thiám", "累", "Tired", "feelings",
     "做一日，真忝。", "tsò chi̍t ji̍t, chin thiám.",
     "做了一天，真累。", "Worked all day, so tired."),
    ("我愛汝", "guá ài lí", "我爱你", "I love you", "feelings",
     "永遠我愛汝。", "éng-oán guá ài lí.",
     "永远爱你。", "I'll love you forever."),

    ("加油", "ka-iû", "加油", "Go for it", "phrases",
     "比賽加油！", "pí-sài ka-iû!",
     "比赛加油！", "Go for it in the match!"),
    ("食飽未", "chia̍h-pá--buē", "吃饱了吗（问候）", "Have you eaten? (greeting)", "phrases",
     "阿伯，食飽未？", "a-peh, chia̍h-pá--buē?",
     "大爷，吃饱了吗？", "Old sir, have you eaten?"),
    ("按呢", "án-ne", "这样", "Like this / this way", "phrases",
     "按呢較好。", "án-ne khah hó.",
     "这样比较好。", "This way is better."),
    ("聽無", "thiaⁿ-bô", "听不懂", "I don't understand", "phrases",
     "對不起，我聽無。", "tùi-put-chū, guá thiaⁿ-bô.",
     "对不起，我听不懂。", "Sorry, I don't follow."),
    ("閣講一遍", "koh kóng chi̍t piàn", "再说一遍", "Say again", "phrases",
     "歹勢，閣講一遍。", "pháiⁿ-sè, koh kóng chi̍t piàn.",
     "不好意思，再说一遍。", "Sorry, say it again."),
    ("汝叫啥物名", "lí kiò siáⁿ-mih miâ", "你叫什么名字", "What's your name?", "phrases",
     "汝叫啥物名？", "lí kiò siáⁿ-mih miâ?",
     "你叫什么名字？", "What's your name?"),
]
