# Cantonese 粤语 — curated core vocab with Jyutping + example sentences.
VOCAB = [
    ("你好", "nei5 hou2", "你好", "Hello", "greetings",
     "你好！好耐冇見。", "nei5 hou2! hou2 noi6 mou5 gin3.",
     "你好！好久不见。", "Hello! Long time no see."),
    ("早晨", "zou2 san4", "早上好", "Good morning", "greetings",
     "早晨，今日做咩？", "zou2 san4, gam1 jat6 zou6 me1?",
     "早上好，今天做什么？", "Good morning, what are you doing today?"),
    ("唔該", "m4 goi1", "谢谢／劳驾", "Thanks / Excuse me", "greetings",
     "唔該晒，幫咗我好多。", "m4 goi1 saai3, bong1 zo2 ngo5 hou2 do1.",
     "太感谢了，帮了我很多。", "Thank you so much, you helped me a lot."),
    ("多謝", "do1 ze6", "感谢（收礼物）", "Thank you (for a gift)", "greetings",
     "多謝你送嘅禮物。", "do1 ze6 nei5 sung3 ge3 lai5 mat6.",
     "谢谢你送的礼物。", "Thank you for the gift."),
    ("對唔住", "deoi3 m4 zyu6", "对不起", "Sorry", "greetings",
     "對唔住，我遲到咗。", "deoi3 m4 zyu6, ngo5 ci4 dou3 zo2.",
     "对不起，我迟到了。", "Sorry, I was late."),
    ("唔緊要", "m4 gan2 jiu3", "没关系", "It's okay / No worries", "greetings",
     "唔緊要啦，下次先啦。", "m4 gan2 jiu3 laa1, haa6 ci3 sin1 laa1.",
     "没关系，下次吧。", "It's okay, next time then."),
    ("拜拜", "baai1 baai3", "再见", "Bye bye", "greetings",
     "我走啦，拜拜！", "ngo5 zau2 laa3, baai1 baai3!",
     "我走了，拜拜！", "I'm leaving, bye!"),

    ("一", "jat1", "1", "One", "numbers",
     "一個就夠。", "jat1 go3 zau6 gau3.",
     "一个就够了。", "One is enough."),
    ("二", "ji6", "2", "Two", "numbers",
     "要兩個，唔該。", "jiu3 loeng5 go3, m4 goi1.",
     "要两个，谢谢。", "Two, please."),
    ("三", "saam1", "3", "Three", "numbers",
     "三點見。", "saam1 dim2 gin3.",
     "三点见。", "See you at three."),
    ("十", "sap6", "10", "Ten", "numbers",
     "等十分鐘。", "dang2 sap6 fan1 zung1.",
     "等十分钟。", "Wait ten minutes."),

    ("今日", "gam1 jat6", "今天", "Today", "time",
     "今日放假。", "gam1 jat6 fong3 gaa3.",
     "今天放假。", "Today is a day off."),
    ("聽日", "ting1 jat6", "明天", "Tomorrow", "time",
     "聽日再講。", "ting1 jat6 zoi3 gong2.",
     "明天再说。", "Let's talk tomorrow."),
    ("尋日", "cam4 jat6", "昨天", "Yesterday", "time",
     "尋日我見到佢。", "cam4 jat6 ngo5 gin3 dou2 keoi5.",
     "昨天我见到他/她了。", "I saw him/her yesterday."),
    ("而家", "ji4 gaa1", "现在", "Now", "time",
     "而家幾點？", "ji4 gaa1 gei2 dim2?",
     "现在几点？", "What time is it now?"),

    ("爸爸", "baa4 baa1", "爸爸", "Dad", "family",
     "爸爸返工去咗。", "baa4 baa1 faan1 gung1 heoi3 zo2.",
     "爸爸上班去了。", "Dad went to work."),
    ("媽媽", "maa4 maa1", "妈妈", "Mom", "family",
     "媽媽煮飯最好食。", "maa4 maa1 zyu2 faan6 zeoi3 hou2 sik6.",
     "妈妈做饭最好吃。", "Mom's cooking is the best."),
    ("朋友", "pang4 jau5", "朋友", "Friend", "family",
     "佢係我朋友。", "keoi5 hai6 ngo5 pang4 jau5.",
     "他/她是我朋友。", "He/She is my friend."),

    ("飯", "faan6", "米饭／饭", "Rice / Meal", "food",
     "食咗飯未？", "sik6 zo2 faan6 mei6?",
     "吃饭了吗？", "Have you eaten?"),
    ("粥", "zuk1", "粥", "Congee", "food",
     "今朝食咗碗粥。", "gam1 ziu1 sik6 zo2 wun2 zuk1.",
     "早上喝了碗粥。", "I had a bowl of congee this morning."),
    ("點心", "dim2 sam1", "茶点", "Dim sum", "food",
     "週末去飲茶食點心。", "zau1 mut6 heoi3 jam2 caa4 sik6 dim2 sam1.",
     "周末去喝茶吃点心。", "On weekends we go for dim sum."),
    ("叉燒", "caa1 siu1", "叉烧", "BBQ pork", "food",
     "叉燒飯一碗。", "caa1 siu1 faan6 jat1 wun2.",
     "一碗叉烧饭。", "One bowl of BBQ pork rice."),
    ("茶", "caa4", "茶", "Tea", "food",
     "唔該，俾杯熱茶。", "m4 goi1, bei2 bui1 jit6 caa4.",
     "麻烦给杯热茶。", "Please give me a hot tea."),
    ("水", "seoi2", "水", "Water", "food",
     "我想飲水。", "ngo5 soeng2 jam2 seoi2.",
     "我想喝水。", "I want to drink water."),
    ("好食", "hou2 sik6", "好吃", "Tasty", "food",
     "呢間餐廳好好食。", "ni1 gaan1 caan1 teng1 hou2 hou2 sik6.",
     "这家餐厅很好吃。", "This restaurant is really tasty."),

    ("喺邊度", "hai2 bin1 dou6", "在哪里", "Where?", "travel",
     "洗手間喺邊度？", "sai2 sau2 gaan1 hai2 bin1 dou6?",
     "洗手间在哪里？", "Where's the restroom?"),
    ("機場", "gei1 coeng4", "机场", "Airport", "travel",
     "機場去市中心要幾耐？", "gei1 coeng4 heoi3 si5 zung1 sam1 jiu3 gei2 noi6?",
     "从机场到市中心要多久？", "How long from airport to downtown?"),
    ("酒店", "zau2 dim3", "酒店", "Hotel", "travel",
     "酒店喺地鐵站旁邊。", "zau2 dim3 hai2 dei6 tit3 zaam6 pong4 bin1.",
     "酒店在地铁站旁边。", "The hotel is next to the subway station."),
    ("左邊", "zo2 bin1", "左边", "Left", "travel",
     "前面左邊轉。", "cin4 min6 zo2 bin1 zyun3.",
     "前面左转。", "Turn left up ahead."),
    ("右邊", "jau6 bin1", "右边", "Right", "travel",
     "右邊個門。", "jau6 bin1 go3 mun4.",
     "右边那个门。", "The door on the right."),

    ("幾多錢", "gei2 do1 cin2", "多少钱", "How much?", "shopping",
     "呢個幾多錢？", "ni1 go3 gei2 do1 cin2?",
     "这个多少钱？", "How much is this?"),
    ("太貴啦", "taai3 gwai3 laa3", "太贵了", "Too expensive", "shopping",
     "太貴啦，平啲得唔得？", "taai3 gwai3 laa3, peng4 di1 dak1 m4 dak1?",
     "太贵了，能便宜点吗？", "Too expensive, can you go cheaper?"),
    ("平", "peng4", "便宜", "Cheap", "shopping",
     "呢度啲嘢好平。", "ni1 dou6 di1 je5 hou2 peng4.",
     "这里东西很便宜。", "Things here are cheap."),

    ("救命", "gau3 meng6", "救命", "Help!", "emergency",
     "救命啊！有賊！", "gau3 meng6 aa3! jau5 caak6!",
     "救命！有贼！", "Help! Thief!"),
    ("警察", "ging2 caat3", "警察", "Police", "emergency",
     "報警！", "bou3 ging2!",
     "报警！", "Call the police!"),
    ("醫院", "ji1 jyun2", "医院", "Hospital", "emergency",
     "最近嘅醫院喺邊度？", "zeoi3 kan5 ge3 ji1 jyun2 hai2 bin1 dou6?",
     "最近的医院在哪里？", "Where's the nearest hospital?"),

    ("開心", "hoi1 sam1", "开心", "Happy", "feelings",
     "見到你好開心。", "gin3 dou2 nei5 hou2 hoi1 sam1.",
     "见到你很开心。", "I'm happy to see you."),
    ("攰", "gui6", "累", "Tired", "feelings",
     "返工返到好攰。", "faan1 gung1 faan1 dou3 hou2 gui6.",
     "上班累死了。", "Work is exhausting."),
    ("我愛你", "ngo5 oi3 nei5", "我爱你", "I love you", "feelings",
     "一生一世，我愛你。", "jat1 sang1 jat1 sai3, ngo5 oi3 nei5.",
     "一生一世，我爱你。", "For all my life, I love you."),

    ("加油", "gaa1 jau2", "加油", "You can do it", "phrases",
     "聽日比賽加油！", "ting1 jat6 bei2 coi3 gaa1 jau2!",
     "明天比赛加油！", "Good luck with tomorrow's competition!"),
    ("冇所謂", "mou5 so2 wai6", "无所谓", "Whatever / doesn't matter", "phrases",
     "食咩都冇所謂。", "sik6 me1 dou1 mou5 so2 wai6.",
     "吃什么都无所谓。", "I don't mind what we eat."),
    ("好吖", "hou2 aa1", "好的", "OK / Sure", "phrases",
     "一齊去飲茶？好吖！", "jat1 cai4 heoi3 jam2 caa4? hou2 aa1!",
     "一起喝茶？好的！", "Want to get dim sum? Sure!"),
    ("唔好意思", "m4 hou2 ji3 si1", "不好意思", "Excuse me / Sorry", "phrases",
     "唔好意思，借過。", "m4 hou2 ji3 si1, ze3 gwo3.",
     "不好意思，借过。", "Excuse me, may I pass?"),
    ("我聽唔明", "ngo5 teng1 m4 ming4", "我听不懂", "I don't understand", "phrases",
     "對唔住，我聽唔明。", "deoi3 m4 zyu6, ngo5 teng1 m4 ming4.",
     "对不起，我听不懂。", "Sorry, I don't understand."),
    ("你叫咩名", "nei5 giu3 me1 meng2", "你叫什么名字", "What's your name?", "phrases",
     "你好，你叫咩名？", "nei5 hou2, nei5 giu3 me1 meng2?",
     "你好，你叫什么名字？", "Hi, what's your name?"),
]
