"""Add a new 'romance' category with curated love/relationship phrases for all 9 languages.
Run: python add_romance.py
Does not affect any other imported vocabulary."""
from database import engine, SessionLocal
import models

models.Base.metadata.create_all(bind=engine)

# Each entry: (word, rom, meaning_zh, meaning_en, example_native, example_rom, example_zh, example_en)
ROMANCE = {
    "zh-cmn": [
        ("我喜欢你", "wǒ xǐ huan nǐ", "表白（轻）", "I like you",
         "我喜欢你，能做我女朋友吗？", "wǒ xǐ huan nǐ, néng zuò wǒ nǚ péng you ma?",
         "我喜欢你，能做我女朋友吗？", "I like you, will you be my girlfriend?"),
        ("亲爱的", "qīn ài de", "称呼爱人", "Darling / Honey",
         "亲爱的，今晚想吃什么？", "qīn ài de, jīn wǎn xiǎng chī shén me?",
         "亲爱的，今晚想吃什么？", "Darling, what do you want for dinner tonight?"),
        ("宝贝", "bǎo bèi", "亲密称呼", "Baby / Sweetie",
         "宝贝，别生气嘛。", "bǎo bèi, bié shēng qì ma.",
         "宝贝，别生气嘛。", "Baby, don't be angry."),
        ("约会", "yuē huì", "相约见面", "Date",
         "这周末我们去约会吧！", "zhè zhōu mò wǒ men qù yuē huì ba!",
         "这周末我们去约会吧！", "Let's go on a date this weekend!"),
        ("女朋友", "nǚ péng you", "女性恋人", "Girlfriend",
         "我有女朋友了。", "wǒ yǒu nǚ péng you le.",
         "我有女朋友了。", "I have a girlfriend now."),
        ("男朋友", "nán péng you", "男性恋人", "Boyfriend",
         "她男朋友对她很好。", "tā nán péng you duì tā hěn hǎo.",
         "她男朋友对她很好。", "Her boyfriend treats her very well."),
        ("你愿意嫁给我吗", "nǐ yuàn yì jià gěi wǒ ma", "求婚", "Will you marry me?",
         "你愿意嫁给我吗？", "nǐ yuàn yì jià gěi wǒ ma?",
         "你愿意嫁给我吗？", "Will you marry me?"),
        ("一辈子", "yí bèi zi", "一生", "Lifetime / Forever",
         "我想陪你一辈子。", "wǒ xiǎng péi nǐ yí bèi zi.",
         "我想陪你一辈子。", "I want to spend my whole life with you."),
        ("暗恋", "àn liàn", "单方面喜欢", "Secret crush",
         "我暗恋她三年了。", "wǒ àn liàn tā sān nián le.",
         "我暗恋她三年了。", "I've had a secret crush on her for three years."),
        ("一见钟情", "yí jiàn zhōng qíng", "一眼爱上", "Love at first sight",
         "我对你是一见钟情。", "wǒ duì nǐ shì yí jiàn zhōng qíng.",
         "我对你是一见钟情。", "For me, it was love at first sight."),
    ],
    "zh-yue": [
        ("我鍾意你", "ngo5 zung1 ji3 nei5", "我喜欢你", "I like you",
         "其實我好鍾意你。", "kei4 sat6 ngo5 hou2 zung1 ji3 nei5.",
         "其实我很喜欢你。", "Actually, I really like you."),
        ("老婆", "lou5 po4", "妻子／亲昵称呼", "Wife / darling (for woman)",
         "老婆，我返到屋企啦。", "lou5 po4, ngo5 faan1 dou3 uk1 kei2 laa3.",
         "老婆，我回家了。", "Honey, I'm home."),
        ("老公", "lou5 gung1", "丈夫／亲昵称呼", "Husband / darling (for man)",
         "老公生日快樂！", "lou5 gung1 saang1 jat6 faai3 lok6!",
         "老公生日快乐！", "Happy birthday, darling!"),
        ("拍拖", "paak3 to1", "谈恋爱", "Dating",
         "佢哋拍拖三年啦。", "keoi5 dei6 paak3 to1 saam1 nin4 laa3.",
         "他们谈恋爱三年了。", "They've been dating for three years."),
        ("男朋友", "naam4 pang4 jau5", "男朋友", "Boyfriend",
         "我男朋友好疼我。", "ngo5 naam4 pang4 jau5 hou2 tung3 ngo5.",
         "我男朋友很疼我。", "My boyfriend treats me really well."),
        ("女朋友", "neoi5 pang4 jau5", "女朋友", "Girlfriend",
         "你有冇女朋友？", "nei5 jau5 mou5 neoi5 pang4 jau5?",
         "你有女朋友吗？", "Do you have a girlfriend?"),
        ("嫁俾我", "gaa3 bei2 ngo5", "嫁给我", "Marry me",
         "你肯嫁俾我嗎？", "nei5 hang2 gaa3 bei2 ngo5 maa3?",
         "你愿意嫁给我吗？", "Will you marry me?"),
        ("一生一世", "jat1 sang1 jat1 sai3", "一辈子", "Forever / lifetime",
         "一生一世愛你。", "jat1 sang1 jat1 sai3 oi3 nei5.",
         "一生一世爱你。", "I'll love you forever."),
        ("親親", "can1 can1", "亲吻", "Kiss",
         "嚟，親親我。", "lai4, can1 can1 ngo5.",
         "来，亲亲我。", "Come, give me a kiss."),
        ("分手", "fan1 sau2", "结束恋爱", "Break up",
         "我同佢分咗手。", "ngo5 tung4 keoi5 fan1 zo2 sau2.",
         "我和他/她分手了。", "I broke up with him/her."),
    ],
    "en": [
        ("I love you", "/aɪ lʌv juː/", "我爱你", "I love you",
         "I love you more than words can say.", None,
         "我爱你，无以言表。", "I love you more than words can say."),
        ("I miss you", "/aɪ mɪs juː/", "我想你", "I miss you",
         "I miss you every single day.", None,
         "我每天都想你。", "I miss you every single day."),
        ("Sweetheart", "/ˈswiːthɑːrt/", "甜心／亲爱的", "Sweetheart",
         "Sweetheart, you look amazing tonight.", None,
         "亲爱的，你今晚真美。", "Sweetheart, you look amazing tonight."),
        ("Darling", "/ˈdɑːrlɪŋ/", "亲爱的", "Darling",
         "Thank you, darling, for everything.", None,
         "亲爱的，谢谢你做的一切。", "Thank you, darling, for everything."),
        ("Girlfriend", "/ˈɡɜːrlfrɛnd/", "女朋友", "Girlfriend",
         "My girlfriend is a doctor.", None,
         "我女朋友是医生。", "My girlfriend is a doctor."),
        ("Boyfriend", "/ˈbɔɪfrɛnd/", "男朋友", "Boyfriend",
         "Her boyfriend is really sweet.", None,
         "她男朋友人很好。", "Her boyfriend is really sweet."),
        ("Will you marry me?", "/wɪl juː ˈmæri miː/", "你愿意嫁给我吗？", "Will you marry me?",
         "Will you marry me? I want to spend my life with you.", None,
         "你愿意嫁给我吗？我想和你共度一生。", "Will you marry me? I want to spend my life with you."),
        ("Forever", "/fərˈɛvər/", "永远", "Forever",
         "I'll love you forever.", None,
         "我永远爱你。", "I'll love you forever."),
        ("Have a crush on", "/hæv ə krʌʃ ɒn/", "暗恋", "Have a crush on",
         "I've had a crush on him since high school.", None,
         "高中起我就暗恋他。", "I've had a crush on him since high school."),
        ("Love at first sight", "/lʌv æt fɜːrst saɪt/", "一见钟情", "Love at first sight",
         "I believe in love at first sight.", None,
         "我相信一见钟情。", "I believe in love at first sight."),
    ],
    "ja": [
        ("好き", "suki", "喜欢", "Like / love",
         "ずっと君のことが好きだった。", "zutto kimi no koto ga suki datta.",
         "我一直喜欢你。", "I've always liked you."),
        ("大好き", "daisuki", "非常喜欢", "Really love",
         "あなたが大好きです。", "anata ga daisuki desu.",
         "我非常喜欢你。", "I really love you."),
        ("会いたい", "aitai", "想见你", "I want to see you",
         "すぐに会いたいよ。", "sugu ni aitai yo.",
         "我好想马上见到你。", "I want to see you right now."),
        ("愛しい", "itoshii", "珍爱的", "Beloved / dear",
         "愛しい人に手紙を書いた。", "itoshii hito ni tegami wo kaita.",
         "给心爱的人写了信。", "I wrote a letter to my beloved."),
        ("付き合う", "tsukiau", "交往", "Date / go out with",
         "僕と付き合ってください。", "boku to tsukiatte kudasai.",
         "请和我交往吧。", "Please go out with me."),
        ("彼氏", "kareshi", "男朋友", "Boyfriend",
         "彼氏とデートに行く。", "kareshi to deeto ni iku.",
         "我和男朋友去约会。", "I'm going on a date with my boyfriend."),
        ("彼女", "kanojo", "女朋友", "Girlfriend",
         "彼女と5年付き合っている。", "kanojo to go nen tsukiatte iru.",
         "和女朋友交往了五年。", "I've been with my girlfriend for five years."),
        ("結婚しよう", "kekkon shiyou", "我们结婚吧", "Let's get married",
         "ずっと一緒にいたい、結婚しよう。", "zutto issho ni itai, kekkon shiyou.",
         "我想一直和你在一起，结婚吧。", "I want to be with you forever — let's marry."),
        ("ずっと", "zutto", "永远／一直", "Always / forever",
         "ずっとそばにいてね。", "zutto soba ni ite ne.",
         "请永远陪在我身边。", "Stay by my side forever, okay?"),
        ("抱きしめる", "dakishimeru", "拥抱", "Hug tightly",
         "強く抱きしめて。", "tsuyoku dakishimete.",
         "紧紧抱住我。", "Hold me tight."),
    ],
    "ko": [
        ("좋아해", "joahae", "我喜欢你（非正式）", "I like you (casual)",
         "사실 너 좋아해.", "sasil neo joahae.",
         "其实我喜欢你。", "Actually, I like you."),
        ("사랑해", "saranghae", "我爱你", "I love you",
         "영원히 사랑해.", "yeongwonhi saranghae.",
         "我永远爱你。", "I'll love you forever."),
        ("보고 싶어", "bogo sipeo", "我想你", "I miss you",
         "많이 보고 싶어.", "mani bogo sipeo.",
         "我好想你。", "I miss you so much."),
        ("자기야", "jagiya", "亲爱的", "Honey / darling",
         "자기야, 오늘 고생했어.", "jagiya, oneul gosaenghaesseo.",
         "亲爱的，今天辛苦了。", "Honey, you worked hard today."),
        ("남자친구", "namjachingu", "男朋友", "Boyfriend",
         "남자친구랑 여행 가요.", "namjachinguRang yeohaeng gayo.",
         "和男朋友去旅行。", "I'm going on a trip with my boyfriend."),
        ("여자친구", "yeojachingu", "女朋友", "Girlfriend",
         "여자친구 생일이에요.", "yeojachingu saengiriyeyo.",
         "是我女朋友的生日。", "It's my girlfriend's birthday."),
        ("결혼하자", "gyeolhonhaja", "我们结婚吧", "Let's get married",
         "평생 같이 있자, 결혼하자.", "pyeongsaeng gachi itja, gyeolhonhaja.",
         "一辈子在一起，结婚吧。", "Let's be together forever — marry me."),
        ("사귀다", "sagida", "交往", "Date",
         "언제부터 사귀었어요?", "eonjebuteo sagwieosseoyo?",
         "你们从什么时候开始交往的？", "Since when have you two been dating?"),
        ("영원히", "yeongwonhi", "永远", "Forever",
         "영원히 내 곁에 있어 줘.", "yeongwonhi nae gyeote isseo jwo.",
         "请永远留在我身边。", "Stay by my side forever."),
        ("안아줘", "anajwo", "抱抱我", "Hug me",
         "꼭 안아줘.", "kkok anajwo.",
         "紧紧抱我。", "Hold me tight."),
    ],
    "fr": [
        ("Je t'aime", "/ʒə tɛm/", "我爱你", "I love you",
         "Je t'aime plus que tout au monde.", None,
         "我爱你胜过一切。", "I love you more than anything."),
        ("Tu me manques", "/ty mə mɑ̃k/", "我想你", "I miss you",
         "Tu me manques tellement.", None,
         "我好想你。", "I miss you so much."),
        ("Mon amour", "/mɔ̃.n‿a.muʁ/", "我的爱", "My love",
         "Bonne nuit, mon amour.", None,
         "晚安，亲爱的。", "Good night, my love."),
        ("Chéri(e)", "/ʃe.ʁi/", "亲爱的", "Darling",
         "Chéri, tu me passes le sel ?", None,
         "亲爱的，帮我递一下盐？", "Darling, pass me the salt?"),
        ("Petit ami", "/pə.ti.t‿a.mi/", "男朋友", "Boyfriend",
         "J'ai rencontré son petit ami.", None,
         "我见过她男朋友了。", "I've met her boyfriend."),
        ("Petite amie", "/pə.ti.t‿a.mi/", "女朋友", "Girlfriend",
         "Ma petite amie est française.", None,
         "我女朋友是法国人。", "My girlfriend is French."),
        ("Veux-tu m'épouser ?", "/vø ty me.pu.ze/", "你愿意嫁给我吗", "Will you marry me?",
         "Je t'aime, veux-tu m'épouser ?", None,
         "我爱你，你愿意嫁给我吗？", "I love you, will you marry me?"),
        ("Pour toujours", "/puʁ tu.ʒuʁ/", "永远", "Forever",
         "Je t'aimerai pour toujours.", None,
         "我会永远爱你。", "I will love you forever."),
        ("Bisous", "/bi.zu/", "亲亲", "Kisses",
         "Bisous, bonne nuit !", None,
         "亲亲，晚安！", "Kisses, good night!"),
        ("Coup de foudre", "/ku də fudʁ/", "一见钟情", "Love at first sight",
         "C'était le coup de foudre.", None,
         "那是一见钟情。", "It was love at first sight."),
    ],
    "es": [
        ("Te quiero", "/te ˈkje.ɾo/", "我爱你（日常）", "I love you (casual)",
         "Te quiero mucho, cariño.", None,
         "我好爱你，亲爱的。", "I love you so much, darling."),
        ("Te amo", "/te ˈa.mo/", "我爱你（深情）", "I love you (deep)",
         "Te amo con toda mi alma.", None,
         "我用全心爱你。", "I love you with all my soul."),
        ("Te extraño", "/te eksˈtɾa.ɲo/", "我想你", "I miss you",
         "Te extraño cada día.", None,
         "我每天都想你。", "I miss you every day."),
        ("Mi amor", "/mi aˈmoɾ/", "我的爱", "My love",
         "Mi amor, ¿cómo estás?", None,
         "亲爱的，你怎么样？", "My love, how are you?"),
        ("Cariño", "/kaˈɾi.ɲo/", "亲爱的", "Darling",
         "Cariño, ¿qué quieres cenar?", None,
         "亲爱的，晚饭想吃什么？", "Darling, what do you want for dinner?"),
        ("Novio", "/ˈno.βjo/", "男朋友", "Boyfriend",
         "Mi novio es músico.", None,
         "我男朋友是音乐家。", "My boyfriend is a musician."),
        ("Novia", "/ˈno.βja/", "女朋友", "Girlfriend",
         "Voy a cenar con mi novia.", None,
         "我要和女朋友吃晚饭。", "I'm having dinner with my girlfriend."),
        ("¿Te casas conmigo?", "/te ˈka.sas konˈmi.ɣo/", "你愿意嫁给我吗", "Will you marry me?",
         "Te amo, ¿te casas conmigo?", None,
         "我爱你，你愿意嫁给我吗？", "I love you, will you marry me?"),
        ("Para siempre", "/ˈpa.ɾa ˈsjem.pɾe/", "永远", "Forever",
         "Estaremos juntos para siempre.", None,
         "我们会永远在一起。", "We'll be together forever."),
        ("Un beso", "/un ˈbe.so/", "一个吻", "A kiss",
         "Dame un beso antes de irte.", None,
         "走之前给我一个吻。", "Give me a kiss before you leave."),
    ],
    "de": [
        ("Ich liebe dich", "/ɪç ˈliːbə dɪç/", "我爱你", "I love you",
         "Ich liebe dich über alles.", None,
         "我爱你胜过一切。", "I love you above all else."),
        ("Ich vermisse dich", "/ɪç fɛɐˈmɪsə dɪç/", "我想你", "I miss you",
         "Ich vermisse dich so sehr.", None,
         "我好想你。", "I miss you so much."),
        ("Schatz", "/ʃats/", "亲爱的／宝贝", "Darling / treasure",
         "Schatz, ich liebe dich.", None,
         "亲爱的，我爱你。", "Darling, I love you."),
        ("Liebling", "/ˈliːplɪŋ/", "心爱的人", "Sweetheart",
         "Mein Liebling, wie geht es dir?", None,
         "亲爱的，你怎么样？", "Sweetheart, how are you?"),
        ("Freund", "/fʁɔʏnt/", "男朋友", "Boyfriend",
         "Mein Freund ist sehr lieb.", None,
         "我男朋友人很好。", "My boyfriend is really sweet."),
        ("Freundin", "/ˈfʁɔʏndɪn/", "女朋友", "Girlfriend",
         "Ich habe eine Freundin.", None,
         "我有女朋友了。", "I have a girlfriend."),
        ("Willst du mich heiraten?", "/vɪlst duː mɪç ˈhaɪʁaːtn̩/", "你愿意嫁给我吗", "Will you marry me?",
         "Ich liebe dich — willst du mich heiraten?", None,
         "我爱你——你愿意嫁给我吗？", "I love you — will you marry me?"),
        ("Für immer", "/fyːɐ ˈɪmɐ/", "永远", "Forever",
         "Ich bleibe für immer bei dir.", None,
         "我会永远在你身边。", "I'll stay with you forever."),
        ("Kuss", "/kʊs/", "吻", "Kiss",
         "Einen Kuss vor dem Schlafen, bitte.", None,
         "睡前一个吻，好吗？", "A kiss before bed, please."),
        ("Liebe auf den ersten Blick", "/ˈliːbə aʊf deːn ˈeːɐstn̩ blɪk/", "一见钟情", "Love at first sight",
         "Es war Liebe auf den ersten Blick.", None,
         "那是一见钟情。", "It was love at first sight."),
    ],
}


def seed_romance():
    db = SessionLocal()
    try:
        code_to_id = {lang.code: lang.id for lang in db.query(models.Language).all()}
        if not code_to_id:
            print("ERROR: no languages found. Run seed_data.py first.")
            return

        # Wipe any previously inserted romance entries so re-running is idempotent
        deleted = (
            db.query(models.VocabItem)
            .filter(models.VocabItem.category == "romance")
            .delete(synchronize_session=False)
        )
        if deleted:
            print(f"Removed {deleted} previous romance entries")
        db.commit()

        count = 0
        for code, items in ROMANCE.items():
            lang_id = code_to_id.get(code)
            if not lang_id:
                print(f"skip {code}: language not in DB")
                continue
            for word, rom, m_zh, m_en, ex_nat, ex_rom, ex_zh, ex_en in items:
                db.add(models.VocabItem(
                    language_id=lang_id,
                    word=word, romanization=rom,
                    meaning_zh=m_zh, meaning_en=m_en,
                    category="romance",
                    example_native=ex_nat, example_romanization=ex_rom,
                    example_zh=ex_zh, example_en=ex_en,
                    source="curated",
                ))
                count += 1
        db.commit()
        print(f"Inserted {count} romance entries across {len(ROMANCE)} languages")
    finally:
        db.close()


if __name__ == "__main__":
    seed_romance()
